/**
 * The English store screenshot world (`npx tsx scripts/seed-store-demo.ts --lang=en`).
 *
 * The same moments as zh-TW.ts, told again as English originals by English
 * writers: a convenience store at 2 a.m., the first morning after quitting,
 * moving out, a father's old bicycle, a grandmother's kitchen. The card ids,
 * who responds to whom, the counts (reads, minutes ago), the paragraph counts,
 * the conversation, the bell and the thought map's geometry all match the
 * zh-TW world one for one, so the same capture plan fits both. Every story is
 * written for this world; none of it is quoted from anywhere.
 */
import { thoughtMap, type CardSpec, type DemoDraft, type DemoWorld, type Writer } from './shared';

const VIEWER: Writer = {
  uid: 'mia',
  handle: 'Mia',
  bio: 'Third year of renting in the city, writing about small everyday things',
  region: 'US',
  accent: 'oklch(89% 0.07 165)',
  joinedDaysAgo: 120,
};

const WRITERS: Writer[] = [
  { uid: 'june', handle: 'June', bio: 'Grew up in a small town. I love to cook, and I love to remember', region: 'CA', accent: 'oklch(88% 0.08 55)', joinedDaysAgo: 210 },
  { uid: 'rosa', handle: 'Rosa', bio: 'Rainy days and quiet cafés are my happy places', region: 'IE', accent: 'oklch(90% 0.05 290)', joinedDaysAgo: 180 },
  { uid: 'theo', handle: 'Theo', bio: 'I write about family, and the things we never said out loud', region: 'GB', accent: 'oklch(90% 0.07 88)', joinedDaysAgo: 150 },
  { uid: 'eli', handle: 'Eli', bio: 'Between jobs, slowly finding my own rhythm again', region: 'AU', accent: 'oklch(90% 0.06 140)', joinedDaysAgo: 95 },
  { uid: 'kai', handle: 'Kai', bio: 'Night-shift worker, collecting the small hours of the city', region: 'NZ', accent: 'oklch(90% 0.05 215)', joinedDaysAgo: 75 },
  { uid: 'noor', handle: 'Noor', bio: 'Living in Kyoto, writing home about everyday life in Japan', region: 'JP', accent: 'oklch(89% 0.07 18)', joinedDaysAgo: 60 },
];

const CARDS: CardSpec[] = [
  // ---- the freshest cards: what the feed opens on ----
  {
    id: 'two-am-convenience-store',
    author: 'kai',
    title: 'The Convenience Store at 2 a.m.',
    hue: 290,
    ago: 18,
    reads: 97,
    tags: ['night', 'city', 'strangers'],
    paragraphs: [
      'At two in the morning I walked into the convenience store on my corner for a bottle of water. Bright as noon inside; in the corner, hot dogs turned slowly on their rollers.',
      'The clerk, restocking shelves, glanced up. “Hey, welcome in.” Not too warm, not too flat, just how you’d greet someone you knew.',
      'I stood by the drinks fridge a long time. I wasn’t thirsty. I just didn’t want to go back to that quiet room.',
      'At the register he set my change in my palm. “Late night, huh? Get some rest.” That was all, and somewhere in my chest a spot felt gently pressed.',
      'Being thought of by a stranger, even for one sentence, can be a light that lasts all night.',
    ],
  },
  {
    id: 'first-morning-after-quitting',
    author: 'eli',
    title: 'The First Morning After Quitting',
    hue: 88,
    ago: 75,
    reads: 312,
    tags: ['work', 'self', 'everyday'],
    paragraphs: [
      'No alarm. The light through the curtains had already crept halfway up the wall, a spot I hadn’t seen on a weekday in years.',
      'I lay listening to the woman downstairs pull her shopping cart past, wheels clicking over the pavement seams. So this is what nine o’clock sounds like.',
      'Yesterday, as I put my badge in the drawer, my hand shook. Seven years of shrinking into a job title, an extension number, and emails that began “Just circling back.” Now I stood in the kitchen, unsure which mug was mine.',
      'I made a slow cup of tea and drank it at the window. No messages, no meetings. The quiet was a little frightening, and a little good.',
      'I don’t know what comes next. But this morning, for the first time, the day felt like mine.',
    ],
  },
  {
    id: 'the-day-i-moved-out',
    author: 'noor',
    title: 'The Day I Moved Out',
    hue: 18,
    ago: 170,
    reads: 528,
    tags: ['moving', 'growth', 'family'],
    paragraphs: [
      'Moving day was almost unkind in how lovely it was. The sun shone, bright and shameless, as if to say this was no day for sadness.',
      'Dad said nothing. He hoisted the last box into the van and tied the rope down twice more. Mum pressed a bag of fruit into my hands, then went inside to check the gas. I knew it was already off.',
      'In the rear-view mirror, the two of them stood at the end of the lane. They didn’t wave. They just got smaller, until a wall took them away.',
      'In the new room I sat on the floor and opened the bag. Every piece of fruit had been washed, dried, and wrapped in tissue. I ate an orange. It was sour, and I finished the whole thing.',
      'That night I texted Mum: “The oranges were so sweet.” She wrote back: “Good. I’m glad.”',
    ],
  },
  {
    id: 'fathers-old-bicycle',
    author: 'theo',
    title: 'My Father’s Old Bicycle',
    hue: 215,
    ago: 340,
    reads: 701,
    tags: ['family', 'memory', 'growth'],
    paragraphs: [
      'A blue bicycle has always leaned in the corner of the garage. The chain is rusty, the saddle split, but Dad keeps taping it up and says it still rides.',
      'Saturday mornings, he’d lift me onto the back and ride to the market for bacon rolls. I held the hem of his shirt, which smelled of soap and sunshine.',
      'I always thought he rode fast. Only later did I learn he rode slowly, afraid I’d fall.',
      'Last month I pumped up the tires and fitted a new saddle. Dad watched, hands in his pockets. “Don’t bother, it’s so old.” But his eyes never left that saddle.',
      'I didn’t call him on it.',
      'I rode a little way down our old road, slowly this time. The seat behind me was empty, yet it felt like someone was holding on to my shirt.',
    ],
  },
  {
    id: 'mint-on-the-balcony',
    author: 'rosa',
    title: 'Mint on the Balcony',
    hue: 140,
    ago: 610,
    reads: 246,
    tags: ['everyday', 'plants', 'healing'],
    paragraphs: [
      'My first weekend in the new place, I put a pot of mint on the balcony. The woman at the garden stall said it was easy: give it light and water, and it does the rest.',
      'I laughed. It sounded like she was talking about me.',
      'Each morning before I leave I touch its leaves, so the cool scent stays on my fingers. It smells like a morning after rain, or like someone who’s just washed their hair walking past.',
      'This month I’ve worked late a lot. One night I got home at eleven and found the mint had grown a whole inch, leaning toward the lamp inside. Even when nobody minds it, it keeps growing, earnestly.',
      'That night I made mint tea and thought: being kept company by a plant, quietly, is already enough.',
    ],
  },

  // ---- “Grandma’s Kitchen” and the resonances it drew ----
  {
    id: 'grandmas-kitchen',
    author: 'june',
    title: 'Grandma’s Kitchen',
    hue: 55,
    ago: 2000,
    reads: 864,
    tags: ['family', 'cooking', 'memory'],
    paragraphs: [
      'Grandma’s kitchen was so small that two people turning at once would bump into each other. The wall by the stove was smoked pale amber, and as a child I thought that was simply the color of time.',
      'Home from school, I knew from the smell what was for dinner. Soy sauce and rock sugar melting in the pot meant braised pork; scallions hitting hot oil meant eggs. She never used a recipe or a measuring spoon. “About right” was her only unit.',
      'I asked her how much that was. She held a spoonful up to the light and said, “Enough that you smile when you taste it.”',
      'Later I ate in many expensive restaurants, but never again a bowl of rice I could eat so freely. She always said, “Have another, there’s plenty of soup.” Back then it only felt noisy. Now I know it was the gentlest thing she knew how to say.',
      'Last month, in my own little kitchen, I finally cooked her braised pork from memory. It came out too sweet. But when I lifted the lid and the steam hit my face, I felt her beside me, smiling: that’s about right.',
    ],
  },
  {
    id: 'rice-cooker-is-waiting-too',
    author: 'mia',
    title: 'My Grandma’s Rice Cooker Waits Too',
    hue: 55,
    ago: 1700,
    reads: 176,
    ref: 'grandmas-kitchen',
    tags: ['response', 'family'],
    paragraphs: [
      'Reading about your grandmother’s kitchen, I kept thinking of the old rice cooker at my grandma’s: cream-colored, a ring of water stain on the pot, a switch that went down with a heavy clunk.',
      'She never used a recipe either. “When the switch pops up, it’s done,” she’d say. I thought that was a brush-off. Now I know it was all the patience she had.',
      'Thank you for giving me back that clunk.',
    ],
  },
  {
    id: 'first-lamp-in-my-rental',
    author: 'mia',
    title: 'The First Lamp in My Rental',
    hue: 88,
    ago: 1500,
    reads: 402,
    tags: ['moving', 'everyday', 'self'],
    paragraphs: [
      'The night I moved into my rental, the ceiling light was broken. The landlord couldn’t come until tomorrow, so I felt my way through the dark, pushing suitcases into the room.',
      'Then I dug a little flea-market desk lamp out of my backpack and plugged it in. Orange light spilled across a small circle of floor, half the desk, and the glass of water I’d set down.',
      'That circle was tiny, but just big enough to sit in. I ate a cold takeout dinner inside it and thought, for the first time, that this small room might slowly become home.',
      'What I remember now isn’t the broken light but that circle of glow. A place only becomes truly yours with the first lamp you light for it.',
    ],
  },
  {
    id: 'a-pot-of-soup-time',
    author: 'rosa',
    title: 'The Time a Pot of Soup Takes',
    hue: 215,
    ago: 1250,
    reads: 120,
    ref: 'grandmas-kitchen',
    tags: ['response', 'cooking'],
    paragraphs: [
      'You said “about right” was her only unit, and I laughed out loud, then felt a little like crying.',
      'My nana was the same. Her soup was never the same twice, but every bowl was exactly what I needed that day.',
    ],
  },
  {
    id: 'that-lamp-reaches-me-too',
    author: 'rosa',
    title: 'That Lamp Shines in My Room Too',
    hue: 290,
    ago: 1000,
    reads: 143,
    ref: 'first-lamp-in-my-rental',
    tags: ['response', 'moving'],
    paragraphs: [
      'I had the exact same night when I moved: the light broken, my bags still in the doorway, the whole room feeling like someone else’s.',
      'After reading your card I switched on my own little lamp too. As the orange glow spread, it felt like someone far away was saying: welcome home.',
    ],
  },
  {
    id: 'soy-sauce-and-rock-sugar',
    author: 'theo',
    title: 'Soy Sauce and Rock Sugar',
    hue: 88,
    ago: 900,
    reads: 98,
    ref: 'grandmas-kitchen',
    tags: ['response', 'family'],
    paragraphs: [
      'Reading about soy sauce and rock sugar melting in the pot, I realized that what I remember of my gran isn’t anything she said, but her back at the stove.',
      'It was such a small back, and yet it seemed to hold up the whole house.',
    ],
  },
  {
    id: 'light-of-a-new-home',
    author: 'june',
    title: 'The Light of a New Home',
    hue: 55,
    ago: 800,
    reads: 87,
    ref: 'first-lamp-in-my-rental',
    tags: ['response', 'everyday'],
    paragraphs: [
      '“A place only becomes truly yours with the first lamp you light for it.” I want to copy that onto a sticky note and put it on my fridge.',
      'Thank you for writing it.',
    ],
  },

  // ---- older cards ----
  {
    id: 'day-three-of-a-solo-trip',
    author: 'kai',
    title: 'Day Three, Traveling Alone',
    hue: 215,
    ago: 3300,
    reads: 410,
    tags: ['travel', 'self', 'sea'],
    paragraphs: [
      'On the third day I finally got used to eating alone. No pretending to check my phone, no rushing, just a bowl of noodles eaten slowly, down to the last of the broth.',
      'I spent a whole afternoon on a small town’s beach. The tide went out and came back, as if saying, no rush, no rush. Nearby, an old couple sat under one parasol, not speaking, as if they had already said everything.',
      'I used to think you travel to see new places. Sometimes it’s to hear your own voice.',
      'On the way home I folded my train ticket into a tiny paper boat and tucked it in my pocket. It won’t float away, but I’m carrying a little of the sea home.',
    ],
  },
  {
    id: 'walk-slower-in-the-rain',
    author: 'rosa',
    title: 'Walk Slower in the Rain',
    hue: 215,
    ago: 4000,
    reads: 388,
    tags: ['walking', 'rain', 'everyday'],
    paragraphs: [
      'I’ve always loved rainy days. Not the wet shoes, but how the city gets turned down a few notches, every sound softened, as if heard through a quilt.',
      'Today I walked to the station without an umbrella, having left mine at the office. The rain was light and cool in my hair, and somewhere along the way I slowed down.',
      'Passing a bakery, I saw its window fogged over and the baker lining up fresh loaves. I stood under the awning so long that my own breath began to fog the glass.',
      'At home I hung up my damp coat and the drops fell onto the floor, one by one, like a very slow song. Sometimes we need the rain to knock our rhythm off, so we remember we’re allowed to go slower.',
    ],
  },
  {
    id: 'slow-steps-in-the-rain-too',
    author: 'mia',
    title: 'I Want to Walk Slowly in the Rain Too',
    hue: 215,
    ago: 3500,
    reads: 166,
    ref: 'walk-slower-in-the-rain',
    tags: ['response', 'walking'],
    paragraphs: [
      'You wrote that the city gets “turned down a few notches,” and as I read it, rain was falling outside my window too.',
      'I opened the window a crack and listened to it on the tin roof across the way, tap, tap, like someone typing very carefully.',
      'Today I’ve decided to walk slower too.',
    ],
  },
  {
    id: 'hotpot-for-one',
    author: 'mia',
    title: 'Hot Pot for One',
    hue: 55,
    ago: 4500,
    reads: 356,
    tags: ['everyday', 'self', 'cooking'],
    paragraphs: [
      'A friend cancelled at the last minute. I stood outside the hot pot restaurant, hesitated three seconds, and went in. “Just one,” I said. The server didn’t blink and led me to a small table by the window.',
      'Hot pot for one is quiet. When the broth rolled, I added a slice of corn, a piece of tofu, a leaf of cabbage, and arranged them in my bowl like a tiny painting.',
      'I used to think eating alone needed an excuse. But that night, steam fogging my glasses, I felt I owed no one an explanation.',
      'When I paid, the server said, “Thanks for choosing us tonight.” I smiled. Looking after yourself, I realized, is a way of being hosted too.',
    ],
  },
  {
    id: 'first-pay-envelope',
    author: 'eli',
    title: 'The Pay Envelope from My First Job',
    hue: 140,
    ago: 5200,
    reads: 455,
    tags: ['work', 'memory', 'growth'],
    paragraphs: [
      'My first job paid in cash. One afternoon at month’s end, my supervisor set a brown paper envelope on my desk, my name on it in crooked ballpoint.',
      'I didn’t dare open it there. On the back row of the bus after work, I tore open one small corner. Nine hundred dollars, bill by bill. I counted it three times.',
      'That month I took my parents to dinner and ordered the most expensive fish on the menu. Dad said it was a waste, then put the best piece on my plate.',
      'I still have that envelope in my bottom desk drawer. There’s no money in it now, only something I’ve never been able to spend.',
    ],
  },
  {
    id: 'the-43rd-minute',
    author: 'mia',
    title: 'The 43rd Minute of My Commute',
    hue: 290,
    ago: 7000,
    reads: 521,
    tags: ['city', 'everyday', 'commute'],
    paragraphs: [
      'My commute takes forty-three minutes, from Queens to Midtown. The morning subway is a packed river, and we’re all pebbles carried along.',
      'The forty-third minute is when I step out of the station. Sunlight cuts in slantwise from the exit, and however I slept, I pause half a second and breathe.',
      'One day the girl across from me was reading an old book of poems, pages yellowed. At one page the corner of her mouth curled up. Everyone in this crowded city, I thought, carries a quiet universe of their own.',
      'That day I put my phone away too. The forty-third minute came, I walked out into the light, and felt today might turn out all right.',
    ],
  },
  {
    id: 'back-row-of-cram-school',
    author: 'theo',
    title: 'The Back Row of Cram School',
    hue: 88,
    ago: 8000,
    reads: 233,
    tags: ['growth', 'youth', 'memory'],
    paragraphs: [
      'In my last year of high school I always sat in the back row of the cram school, by the window, where I could see the lights in the building across the street burning late.',
      'I wondered if behind those windows someone like me was working through the same endless practice papers. It made me feel less alone.',
      'One night after class a downpour hit. Everyone had left, and I stood under the awning until a girl I barely knew held out her umbrella. “I live really close, you take it.” She ran off into the rain before I could ask her name.',
      'I’ve forgotten every exam question from that year, but I still remember that umbrella: pale blue, one rib slightly bent.',
    ],
  },
  {
    id: 'night-train-home',
    author: 'june',
    title: 'The Night Train Home',
    hue: 290,
    ago: 9500,
    reads: 305,
    tags: ['travel', 'family', 'night'],
    paragraphs: [
      'The Friday night train is always packed with people heading home. I sit by the window and watch the lights slide away, as if time were running backward.',
      'The old man beside me held a big paper bag of cinnamon buns, still steaming, close to his chest so no one would squash them. They were for his grandson, he said.',
      'I suddenly remembered I should call home. It rang twice, and Mom picked up. “Where are you now? I’ve kept supper warm.”',
      'The train kept heading south. Dark outside, but I knew a light had been left on for me somewhere ahead.',
    ],
  },
  {
    id: 'mothers-phone-call',
    author: 'mia',
    title: 'A Call from Mom',
    hue: 18,
    ago: 10500,
    reads: 288,
    tags: ['family', 'everyday', 'missing'],
    paragraphs: [
      'Mom rarely calls. She worries I’m busy, worries she’ll disturb me, so mostly she sends stickers: a bear holding flowers, a cat making a heart.',
      'Last night at ten my phone rang. “Mom.” My heart skipped. When I picked up, she only said, “Nothing’s wrong, I just wanted to see if you’d eaten.”',
      'I said I had, though really I’d had a bag of crackers. “Good, take care of yourself.” Then we were quiet, and I could hear a loud soap opera on the TV behind her.',
      'I keep thinking about that minute of quiet. Some love doesn’t need words. It only needs someone on the other end, keeping you company.',
    ],
  },
  {
    id: 'first-winter-abroad',
    author: 'noor',
    title: 'My First Winter Abroad',
    hue: 215,
    ago: 12000,
    reads: 190,
    tags: ['abroad', 'winter', 'self'],
    paragraphs: [
      'My first winter in this city, I learned plenty: how to sort the trash, how to walk on snow without slipping, how to buy a hot rice ball at the convenience store in imperfect Japanese.',
      'Evenings were hardest. Dark fell before five, leaving only streetlights outside my window. I sat listening to the heater and missed the dim, warm lamp at home.',
      'One day my landlady knocked and handed me a bowl of hot soup. “It’s so cold, and you’re all alone. Eat more.” I thanked her in broken Japanese, and she smiled and waved it off.',
      'I drank that soup slowly. Where there’s no shared language, it turns out, warmth is understood anyway.',
    ],
  },
  {
    id: 'sunday-market',
    author: 'mia',
    title: 'The Sunday Market',
    hue: 140,
    ago: 14000,
    reads: 199,
    tags: ['everyday', 'memory', 'walking'],
    paragraphs: [
      'On Sunday mornings I walk to the neighborhood market. Stalls one after another, the fishmonger’s hose, the vegetable sellers calling out, the smell of fresh-fried doughnuts, all mixed together. My favorite kind of busy.',
      'The woman I buy vegetables from remembers I don’t like cilantro. She tucks extra scallions into my bag. “This one’s on me today.”',
      'That day I thought: being remembered is the smallest, and biggest, kindness this city has.',
    ],
  },
];

const DRAFT: DemoDraft = {
  id: 'draft-the-night-of-the-blackout',
  title: 'The Night of the Blackout',
  story: [
    'At nine the whole building went quiet. The fridge stopped humming, my screen went dark, even the TV next door fell silent.',
    'I felt my way to the drawer and lit a candle. The flame wavered, stretching the shadows long across the wall. This room I’d lived in for three years felt more like home by candlelight than ever.',
  ],
  ago: 15,
};

export const en: DemoWorld = {
  lang: 'en',
  autoTranslateTo: ['zh-TW'],
  viewer: VIEWER,
  writers: WRITERS,
  cards: CARDS,
  draft: DRAFT,
  // Kai's card that links to one of hers (the bell's card_link, and her card box's "linked" shelf).
  cardLink: { source: 'day-three-of-a-solo-trip', target: 'the-43rd-minute', ago: 120 },
  // ---- the conversation with June about “Grandma’s Kitchen” ----
  partner: 'june',
  originCardId: 'grandmas-kitchen',
  messages: [
    { from: 'june', ago: 1480, text: 'Your reply to “Grandma’s Kitchen” almost made me cry' },
    { from: 'mia', ago: 1450, text: 'I should be thanking you. I read “about right” five times' },
    { from: 'june', ago: 1420, text: 'That rice cooker clunk took me right back to being a kid' },
    { from: 'mia', ago: 1400, text: 'Same here. That sound still feels so safe' },
    { from: 'mia', ago: 1395, cardRef: 'mothers-phone-call', text: 'I once wrote about Mom’s calls. Same comfort as your kitchen' },
    { from: 'june', ago: 300, text: 'Just read it. I know that quiet' },
    { from: 'june', ago: 25, text: 'I’ll cook the braised pork again, with less sugar. You’ll get the story first' },
  ],
  // ---- the bell (three unread, one read) ----
  notifications: [
    { id: 'n-card-link', type: 'card_link', from: 'kai', ago: 120, extra: { sourceCardId: 'day-three-of-a-solo-trip', cardId: 'the-43rd-minute' } },
    { id: 'n-resonance-june', type: 'resonance', from: 'june', ago: 800, extra: { cardId: 'first-lamp-in-my-rental' } },
    { id: 'n-resonance-rosa', type: 'resonance', from: 'rosa', ago: 1000, extra: { cardId: 'first-lamp-in-my-rental' } },
    { id: 'n-message-june', type: 'message', from: 'june', ago: 1480, read: true, extra: {} },
  ],
  // ---- her thought map: two labelled zones, six of her cards, three labelled arrows ----
  map: thoughtMap({ alone: 'Living alone', remembered: 'Kindness remembered' }, { later: 'Later', missing: 'Missing', extends: 'Leads to' }),
};
