/**
 * The web's hand-drawn icons → path data for the native apps.
 *
 * Renders every icon in src/components/atoms/Icon/registry.ts (plus the
 * verified checkmark) to SVG markup, checks it only uses what the apps can
 * draw — absolute M/L/C/Z paths, stroked with the icon's color or filled
 * with it — and writes each path as a flat command list:
 * 0 x y = move, 1 x y = line, 2 x1 y1 x2 y2 x y = curve, 3 = close.
 *
 *   npx tsx scripts/apps/icons.ts          (part of `npm run apps:generate`)
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import * as React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

const root = resolve(__dirname, '../..');
// The icon modules use the classic JSX runtime under tsx.
(globalThis as { React?: typeof React }).React = React;

const COLOR = '#010203';
const FILL = '#040506';
const PEN = 2;

interface Stroke {
  commands: number[];
  filled: boolean;
  width: number;
}
interface Glyph {
  name: string;
  viewBox: number;
  fillable: boolean;
  strokes: Stroke[];
}

function attrs(tag: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const m of tag.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) out[m[1]] = m[2];
  return out;
}

function commands(d: string, where: string): number[] {
  const out: number[] = [];
  const tokens = d.match(/[A-Za-z]|-?\d*\.?\d+(?:e-?\d+)?/g) ?? [];
  const arity: Record<string, [number, number]> = { M: [0, 2], L: [1, 2], C: [2, 6], Z: [3, 0] };
  let i = 0;
  let op = '';
  while (i < tokens.length) {
    if (/[A-Za-z]/.test(tokens[i])) op = tokens[i++];
    const spec = arity[op];
    if (!spec) throw new Error(`${where}: path command "${op}" — the apps draw only absolute M/L/C/Z`);
    const args = tokens.slice(i, i + spec[1]).map(Number);
    if (args.length !== spec[1] || args.some(Number.isNaN)) throw new Error(`${where}: bad arguments for ${op}`);
    out.push(spec[0], ...args);
    i += spec[1];
    if (op === 'M') op = 'L'; // implicit lineto after a moveto
    if (op === 'Z') op = '';
  }
  return out;
}

function glyph(name: string, markup: string): Glyph {
  const svg = attrs(markup.match(/<svg[^>]*>/)![0]);
  const viewBox = Number(svg.viewBox.split(/\s+/)[2]);
  const pen = Number(svg['stroke-width'] ?? PEN);
  const strokes: Stroke[] = [];
  const unsupported = markup.match(/<(circle|ellipse|rect|line|polyline|polygon|g|use)\b/);
  if (unsupported) throw new Error(`${name}: <${unsupported[1]}> — draw it as a path`);
  for (const [tag] of markup.matchAll(/<path[^>]*>/g)) {
    const a = attrs(tag);
    const filled = a.fill === COLOR && a.stroke === 'none';
    if (!filled && a.fill && a.fill !== 'none') throw new Error(`${name}: a path filled with something other than the icon's color`);
    strokes.push({ commands: commands(a.d, name), filled, width: +(Number(a['stroke-width'] ?? pen) / PEN).toFixed(3) });
  }
  return { name, viewBox, fillable: svg.fill === FILL, strokes };
}

function camel(name: string) {
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}
const num = (n: number) => (Number.isInteger(n) ? `${n}` : `${n}`);

void (async () => {
  const { ICONS } = await import('../../src/components/atoms/Icon/registry');
  const { HandDrawnCheckmark } = await import('../../src/components/atoms/HandDrawnCheckmark/HandDrawnCheckmark');
  const render = (c: React.ComponentType<Record<string, unknown>>, props: Record<string, unknown>) =>
    renderToStaticMarkup(React.createElement(c, props));

  const glyphs: Glyph[] = Object.entries(ICONS).map(([name, R]) =>
    glyph(name, render(R as React.ComponentType<Record<string, unknown>>, { size: 24, color: COLOR, strokeWidth: PEN, fill: FILL })),
  );
  // The verified mark beside an author's name (atoms/HandDrawnCheckmark).
  glyphs.push(glyph('verified', render(HandDrawnCheckmark as React.ComponentType<Record<string, unknown>>, { size: 16, color: COLOR, strokeWidth: PEN })));

  const header = 'Generated by scripts/apps/icons.ts from src/components/atoms/Icon — do not edit.';

  const swift = `// ${header}
// Commands: 0 x y = move, 1 x y = line, 2 x1 y1 x2 y2 x y = curve, 3 = close.

/// The web's hand-drawn icons, by their registry names.
public enum IconName: String, CaseIterable, Sendable {
${glyphs.map((g) => `    case ${camel(g.name)}${camel(g.name) === g.name ? '' : ` = "${g.name}"`}`).join('\n')}
}

extension IconName {
    nonisolated var glyph: IconGlyph {
        switch self {
${glyphs
  .map(
    (g) =>
      `        case .${camel(g.name)}: IconGlyph(viewBox: ${g.viewBox}, fillable: ${g.fillable}, strokes: [\n` +
      g.strokes
        .map((s) => `            IconStroke(filled: ${s.filled}, width: ${num(s.width)}, commands: [${s.commands.map(num).join(', ')}]),`)
        .join('\n') +
      `\n        ])`,
  )
  .join('\n')}
        }
    }
}
`;

  const pascal = (name: string) => camel(name)[0].toUpperCase() + camel(name).slice(1);
  const kotlin = `// ${header}
// Commands: 0 x y = move, 1 x y = line, 2 x1 y1 x2 y2 x y = curve, 3 = close.
package com.resonance.design.generated

import com.resonance.design.IconGlyph
import com.resonance.design.IconStroke

/** The web's hand-drawn icons, by their registry names. */
enum class IconName(val key: String) {
${glyphs.map((g) => `    ${pascal(g.name)}("${g.name}"),`).join('\n')}
    ;

    val glyph: IconGlyph
        get() = when (this) {
${glyphs
  .map(
    (g) =>
      `            ${pascal(g.name)} -> IconGlyph(${g.viewBox}f, fillable = ${g.fillable}, strokes = listOf(\n` +
      g.strokes
        .map((s) => `                IconStroke(filled = ${s.filled}, width = ${num(s.width)}f, commands = floatArrayOf(${s.commands.map((n) => `${num(n)}f`).join(', ')})),`)
        .join('\n') +
      `\n            ))`,
  )
  .join('\n')}
        }
}
`;

  const outputs: [string, string][] = [
    ['apps/ios/Packages/DesignSystem/Sources/DesignSystem/Generated/Icons.swift', swift],
    ['apps/android/core/design/src/main/kotlin/com/resonance/design/generated/Icons.kt', kotlin],
  ];
  for (const [out, body] of outputs) {
    mkdirSync(dirname(resolve(root, out)), { recursive: true });
    writeFileSync(resolve(root, out), body);
  }
  console.log(`${glyphs.length} icons → Swift + Kotlin`);
})();
