/**
 * src/messages/*.json → typed string accessors for the native apps.
 *
 * The apps read the web's message catalogs themselves (bundled as-is) and
 * format them with a small ICU subset (named arguments, `plural` with `=N`,
 * `one`, `other` and `#`) — the only features the catalogs use, checked
 * below. This script only generates the accessors, so a key that the web
 * renames or removes breaks the app's build instead of showing a raw key.
 *
 *   npx tsx scripts/apps/l10n.ts          (part of `npm run apps:generate`)
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(__dirname, '../..');
const LOCALES = ['en', 'zh-TW'] as const;

type Tree = { [key: string]: string | Tree };
const catalogs = Object.fromEntries(
  LOCALES.map((l) => [l, JSON.parse(readFileSync(resolve(root, `src/messages/${l}.json`), 'utf8')) as Tree]),
) as Record<(typeof LOCALES)[number], Tree>;

/** Arguments a message takes, in order of first appearance, and whether each is a plural count. */
function argsOf(message: string): { name: string; plural: boolean }[] {
  const out = new Map<string, boolean>();
  // Only top-level `{…}` are arguments; text inside plural branches is not.
  for (let i = 0; i < message.length; i++) {
    if (message[i] !== '{') continue;
    let depth = 0;
    let j = i;
    for (; j < message.length; j++) {
      if (message[j] === '{') depth++;
      else if (message[j] === '}' && --depth === 0) break;
    }
    const body = message.slice(i + 1, j);
    const m = /^\s*([A-Za-z_]\w*)\s*(?:,\s*(\w+)\s*,)?/.exec(body);
    if (!m) throw new Error(`Unparseable argument "{${body}}" in: ${message}`);
    if (m[2] && m[2] !== 'plural') throw new Error(`Unsupported ICU argument type "${m[2]}" in: ${message}`);
    if (!m[2] && m[0].trim() !== body.trim()) throw new Error(`Unparseable argument "{${body}}" in: ${message}`);
    out.set(m[1], (out.get(m[1]) ?? false) || m[2] === 'plural');
    i = j;
  }
  return [...out].map(([name, plural]) => ({ name, plural }));
}

const NUMERIC = new Set(['count', 'n', 'days', 'total', 'current']);
const SWIFT_KEYWORDS = new Set(
  'associatedtype class deinit enum extension fileprivate func import init inout internal let open operator private precedencegroup protocol public rethrows static struct subscript typealias var break case catch continue default defer do else fallthrough for guard if in repeat return throw switch where while as false is nil self Self super throws true try Any Type some any'.split(
    ' ',
  ),
);
const ident = (s: string) => {
  const id = s.replace(/[^A-Za-z0-9_]/g, '_').replace(/^(\d)/, '_$1');
  return SWIFT_KEYWORDS.has(id) ? `\`${id}\`` : id;
};
const typeName = (s: string) => {
  const id = s.replace(/[^A-Za-z0-9_]/g, '_');
  return id[0].toUpperCase() + id.slice(1);
};
const escape = (s: string) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');

const warnings: string[] = [];
let keyCount = 0;

function lookup(tree: Tree, path: string[]): string | Tree | undefined {
  let node: string | Tree | undefined = tree;
  for (const p of path) node = typeof node === 'object' ? node[p] : undefined;
  return node;
}

function emit(tree: Tree, path: string[], indent: string): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(tree)) {
    const here = [...path, key];
    const dotted = here.join('.');
    if (typeof value === 'object') {
      lines.push(`${indent}public enum ${typeName(key)} {`);
      lines.push(emit(value, here, `${indent}    `));
      lines.push(`${indent}}`);
      continue;
    }
    keyCount++;
    const variants = LOCALES.map((l) => lookup(catalogs[l], here)).filter((v): v is string => typeof v === 'string');
    for (const l of LOCALES) if (typeof lookup(catalogs[l], here) !== 'string') warnings.push(`${dotted} missing in ${l}`);
    const args = new Map<string, boolean>();
    for (const v of variants) for (const a of argsOf(v)) args.set(a.name, (args.get(a.name) ?? false) || a.plural);
    const doc = `${indent}/// ${escape(value).slice(0, 120)}`;
    if (args.size === 0) {
      lines.push(doc, `${indent}public static var ${ident(key)}: String { Strings.shared.string("${dotted}") }`);
    } else {
      const params = [...args].map(([name, plural]) => `${ident(name)}: ${plural || NUMERIC.has(name) ? 'Int' : 'String'}`);
      const dict = [...args.keys()].map((name) => `"${name}": ${ident(name)}`).join(', ');
      lines.push(
        doc,
        `${indent}public static func ${ident(key)}(${params.join(', ')}) -> String { Strings.shared.format("${dotted}", [${dict}]) }`,
      );
    }
  }
  return lines.join('\n');
}

const swift = `// Generated by scripts/apps/l10n.ts from src/messages — do not edit.
// The strings themselves are read at runtime from the bundled catalogs.
// swiftlint:disable all

public enum L10n {
${emit(catalogs.en, [], '    ')}
}
`;

const out = 'apps/ios/Packages/ResonanceKit/Sources/ResonanceKit/Localization/L10n.swift';
mkdirSync(dirname(resolve(root, out)), { recursive: true });
writeFileSync(resolve(root, out), swift);
console.log(`${keyCount} keys → ${out}`);
for (const w of warnings) console.warn(`  warning: ${w}`);
