package com.resonance.spikes.s6

import android.util.Log
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.safeDrawingPadding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.resonance.api.apis.DefaultApi
import com.resonance.api.infrastructure.ClientError
import com.resonance.api.infrastructure.ClientException
import com.resonance.api.models.ApiError
import com.resonance.api.models.CreateInviteRequest
import com.resonance.spikes.generated.Tokens
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody

/**
 * S6 on Android — the DefaultApi client is generated by openapi-generator
 * (kotlin, okhttp4, kotlinx.serialization) from the same openapi/v1/openapi.json
 * as the iOS client. Auth is the Firebase ID token as a Bearer header.
 *
 *   adb shell am start -n com.resonance.spikes/.MainActivity --es spike api --es run 1 \
 *     --es email alice@resonance.test --es password <seed password>
 * (10.0.2.2 is the host machine from the emulator.)
 */
data class ApiArgs(val api: String, val auth: String, val email: String?, val password: String?)

private val json = Json { ignoreUnknownKeys = true }

@Composable
fun ApiSpike(args: ApiArgs, autorun: Boolean) {
    val log = remember { mutableStateListOf<String>() }
    fun report(line: String) {
        log += line
        Log.i("S6", "S6RESULT $line")
    }
    LaunchedEffect(autorun) {
        if (!autorun) return@LaunchedEffect
        withContext(Dispatchers.IO) { run(args, ::report) }
    }
    LazyColumn(Modifier.fillMaxSize().background(Tokens.Cream).safeDrawingPadding().padding(16.dp)) {
        items(log) { Text(it, fontFamily = FontFamily.Monospace, fontSize = 12.sp) }
    }
}

private fun apiError(e: ClientException): ApiError? =
    ((e.response as? ClientError<*>)?.body as? String)?.let { runCatching { json.decodeFromString(ApiError.serializer(), it) }.getOrNull() }

private fun run(args: ApiArgs, report: (String) -> Unit) {
    if (args.email == null || args.password == null) return report("missing email / password extras")
    try {
        // 1. No token → the contract's 401 (ApiError body).
        try {
            DefaultApi(args.api).getMe()
            report("no token → unexpected 200")
        } catch (e: ClientException) {
            report("no token → ${e.statusCode} ${apiError(e)?.error?.code}")
        }

        // 2. Sign in (Auth emulator REST, as the Firebase SDK does) → ID token.
        val token = signIn(args)
        val http = OkHttpClient.Builder()
            .addInterceptor { chain -> chain.proceed(chain.request().newBuilder().header("Authorization", "Bearer $token").build()) }
            .build()
        val api = DefaultApi(args.api, http)

        // 3. Typed calls.
        val me = api.getMe()
        report("me → @${me.handle} (${me.initials})")
        val page = api.getFeed(limit = 5)
        report("feed → ${page.cards.size} cards: " + page.cards.joinToString(" | ") { "${it.title} by ${it.author?.handle ?: "anonymous"}" })
        for (attempt in 1..2) {
            try {
                val created = api.createInvite(CreateInviteRequest(toUserId = "carol", message = "從 Android 送出的邀請"))
                report("invite #$attempt → 201 id=${created.id}")
            } catch (e: ClientException) {
                report("invite #$attempt → ${e.statusCode} ${apiError(e)?.error?.message}")
            }
        }
        try {
            api.createInvite(CreateInviteRequest(toUserId = "carol", message = "   "))
            report("blank message → unexpected 201")
        } catch (e: ClientException) {
            val err = apiError(e)?.error
            report("blank message → ${e.statusCode} ${err?.code} at ${err?.issues?.map { it.path }}")
        }
        report("done")
    } catch (e: Exception) {
        report("error: $e")
    }
}

@Serializable
private data class SignInResponse(val idToken: String)

private fun signIn(args: ApiArgs): String {
    val body = """{"email":${Json.encodeToString(args.email)},"password":${Json.encodeToString(args.password)},"returnSecureToken":true}"""
    val req = Request.Builder()
        .url("${args.auth}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=demo-key")
        .post(body.toRequestBody("application/json".toMediaType()))
        .build()
    OkHttpClient().newCall(req).execute().use { res ->
        return json.decodeFromString(SignInResponse.serializer(), res.body!!.string()).idToken
    }
}
