import { NextResponse } from 'next/server';
import spec from '../../../../../openapi/v1/openapi.json';

/** The v1 contract, for API tools. The file is generated by `npm run api:openapi`. */
export function GET() {
  return NextResponse.json(spec);
}
