import spec from '../../../../../openapi/v1/openapi.json';
import { etagOf, noneMatchHits } from '@/lib/api/v1/cache';

const body = JSON.stringify(spec);
const etag = etagOf(body);
/** The same for everyone, and changed only by a deploy: any cache may keep it for an hour. */
const CACHE = 'public, max-age=3600';

/** The v1 contract, for API tools. The file is generated by `npm run api:openapi`. */
export function GET(req: Request) {
  const headers = { 'Cache-Control': CACHE, ETag: etag };
  if (noneMatchHits(req.headers.get('If-None-Match'), etag)) return new Response(null, { status: 304, headers });
  return new Response(body, { headers: { ...headers, 'Content-Type': 'application/json' } });
}
