// Generated by scripts/apps/l10n.ts from src/messages — do not edit.
// The strings themselves are read at runtime from the bundled catalogs.
@file:Suppress("unused", "ObjectPropertyName", "FunctionName", "ClassName")

package com.resonance.kit.l10n

object L10n {
    object Metadata {
        /** Resonance — Let lives influence lives */
        val title: String get() = Strings.string("metadata.title")
        /** A space for real life stories from around the world to connect. */
        val description: String get() = Strings.string("metadata.description")
    }
    object Nav {
        /** About */
        val about: String get() = Strings.string("nav.about")
        /** Explore */
        val explore: String get() = Strings.string("nav.explore")
        /** Stories */
        val stories: String get() = Strings.string("nav.stories")
        /** Sign In */
        val signIn: String get() = Strings.string("nav.signIn")
        /** 中 */
        val languageSwitch: String get() = Strings.string("nav.languageSwitch")
        /** Open menu */
        val openMenu: String get() = Strings.string("nav.openMenu")
        /** Site navigation */
        val siteNav: String get() = Strings.string("nav.siteNav")
    }
    object Hero {
        /** ✦ Real life stories */
        val tag: String get() = Strings.string("hero.tag")
        /** Let lives  */
        val headlinePrefix: String get() = Strings.string("hero.headlinePrefix")
        /** influence */
        val headlineAccent: String get() = Strings.string("hero.headlineAccent")
        /**  lives */
        val headlineSuffix: String get() = Strings.string("hero.headlineSuffix")
        /** A space for real life stories from around the world to connect. Read, share, and resonate with the experiences that shap */
        val description: String get() = Strings.string("hero.description")
        /** Explore stories */
        val explore: String get() = Strings.string("hero.explore")
        /** Share your story */
        val share: String get() = Strings.string("hero.share")
        /** Be among the first storytellers here */
        val proof: String get() = Strings.string("hero.proof")
    }
    object Feed {
        /** Latest stories */
        val tag: String get() = Strings.string("feed.tag")
        /** Stories worth reading */
        val title: String get() = Strings.string("feed.title")
        /** Real people, real experiences — every voice carries a world. */
        val subtitle: String get() = Strings.string("feed.subtitle")
        /** View all stories */
        val viewAll: String get() = Strings.string("feed.viewAll")
    }
    object Cta {
        /** Share your story and let the world hear your voice */
        val title: String get() = Strings.string("cta.title")
        /** Every story matters. Yours might be the one that changes someone’s day. */
        val description: String get() = Strings.string("cta.description")
        /** Start sharing */
        val start: String get() = Strings.string("cta.start")
        /** Create a story */
        val create: String get() = Strings.string("cta.create")
    }
    object Footer {
        /** Let lives influence lives */
        val tagline: String get() = Strings.string("footer.tagline")
        /** About */
        val about: String get() = Strings.string("footer.about")
        /** Contact */
        val contact: String get() = Strings.string("footer.contact")
        /** Privacy */
        val privacy: String get() = Strings.string("footer.privacy")
        /** Terms */
        val terms: String get() = Strings.string("footer.terms")
        /** © 2026 Resonance. All rights reserved. */
        val copyright: String get() = Strings.string("footer.copyright")
    }
    object Tweaks {
        /** Tweaks */
        val title: String get() = Strings.string("tweaks.title")
        /** Open tweaks panel */
        val open: String get() = Strings.string("tweaks.open")
        /** Close tweaks panel */
        val close: String get() = Strings.string("tweaks.close")
        /** Accent color */
        val accentColor: String get() = Strings.string("tweaks.accentColor")
        /** Terracotta (default) */
        val accentTerracotta: String get() = Strings.string("tweaks.accentTerracotta")
        /** Sage */
        val accentSage: String get() = Strings.string("tweaks.accentSage")
        /** Lavender */
        val accentLavender: String get() = Strings.string("tweaks.accentLavender")
        /** Yellow */
        val accentYellow: String get() = Strings.string("tweaks.accentYellow")
        /** Heading font */
        val fontFamily: String get() = Strings.string("tweaks.fontFamily")
        /** Playfair Display (default) */
        val fontDefault: String get() = Strings.string("tweaks.fontDefault")
        /** Handwritten */
        val fontHandwritten: String get() = Strings.string("tweaks.fontHandwritten")
        /** Card density */
        val cardDensity: String get() = Strings.string("tweaks.cardDensity")
        /** Normal (3 col) */
        val densityNormal: String get() = Strings.string("tweaks.densityNormal")
        /** Compact (4 col) */
        val densityCompact: String get() = Strings.string("tweaks.densityCompact")
        /** Airy (2 col) */
        val densityAiry: String get() = Strings.string("tweaks.densityAiry")
        /** Grain */
        val grainIntensity: String get() = Strings.string("tweaks.grainIntensity")
        /** None */
        val grainNone: String get() = Strings.string("tweaks.grainNone")
        /** Soft */
        val grainSoft: String get() = Strings.string("tweaks.grainSoft")
        /** Medium */
        val grainMedium: String get() = Strings.string("tweaks.grainMedium")
        /** Heavy */
        val grainHeavy: String get() = Strings.string("tweaks.grainHeavy")
    }
    object App {
        object Nav {
            /** Resonance Feed */
            val home: String get() = Strings.string("app.nav.home")
            /** My Card Box */
            val me: String get() = Strings.string("app.nav.me")
            /** Write */
            val write: String get() = Strings.string("app.nav.write")
            /** Notifications */
            val notifications: String get() = Strings.string("app.nav.notifications")
            /** Settings */
            val settings: String get() = Strings.string("app.nav.settings")
            /** Sign in */
            val signIn: String get() = Strings.string("app.nav.signIn")
            /** Sign out */
            val signOut: String get() = Strings.string("app.nav.signOut")
            /** Messages */
            val messages: String get() = Strings.string("app.nav.messages")
            /** Back */
            val back: String get() = Strings.string("app.nav.back")
            /** Open menu */
            val openMenu: String get() = Strings.string("app.nav.openMenu")
            /** Edit this card */
            val editThisCard: String get() = Strings.string("app.nav.editThisCard")
        }
        object Notifications {
            /** When someone resonates with your card — or sends you a little note — it will show up here. */
            val empty: String get() = Strings.string("app.notifications.empty")
            /** {handle} wants to connect */
            fun invite(handle: String): String = Strings.format("app.notifications.invite", mapOf("handle" to handle))
            /** {handle} accepted your invite — you're connected ✿ */
            fun inviteAccepted(handle: String): String = Strings.format("app.notifications.inviteAccepted", mapOf("handle" to handle))
            /** {count} people resonated with you yesterday */
            fun resonanceSummary(count: Int): String = Strings.format("app.notifications.resonanceSummary", mapOf("count" to count))
            /** Translation complete */
            val translationDone: String get() = Strings.string("app.notifications.translationDone")
            /** {handle} resonated with your card */
            fun resonance(handle: String): String = Strings.format("app.notifications.resonance", mapOf("handle" to handle))
            /** {handle} sent you a little note */
            fun note(handle: String): String = Strings.format("app.notifications.note", mapOf("handle" to handle))
            /** {handle} linked a card to your card */
            fun cardLink(handle: String): String = Strings.format("app.notifications.cardLink", mapOf("handle" to handle))
            /** Connect with them */
            val connect: String get() = Strings.string("app.notifications.connect")
            /** Connected */
            val alreadyConnected: String get() = Strings.string("app.notifications.alreadyConnected")
            /** View all */
            val viewAll: String get() = Strings.string("app.notifications.viewAll")
            /** {handle} sent you a message. */
            fun message(handle: String): String = Strings.format("app.notifications.message", mapOf("handle" to handle))
        }
        object SignOutConfirm {
            /** Sign out? */
            val title: String get() = Strings.string("app.signOutConfirm.title")
            /** You'll need to sign in again to get back to your card box. */
            val body: String get() = Strings.string("app.signOutConfirm.body")
            /** Sign out */
            val confirm: String get() = Strings.string("app.signOutConfirm.confirm")
            /** Cancel */
            val cancel: String get() = Strings.string("app.signOutConfirm.cancel")
        }
    }
    object Home {
        /** Stories picked for you */
        val heading: String get() = Strings.string("home.heading")
        /** Chosen from the insights you have written, alongside the newest public cards. */
        val subheading: String get() = Strings.string("home.subheading")
        /** Load more */
        val moreBtn: String get() = Strings.string("home.moreBtn")
        /** Loading… */
        val moreLoading: String get() = Strings.string("home.moreLoading")
        /** You are caught up on the latest public cards */
        val endOfDay: String get() = Strings.string("home.endOfDay")
        /** Write a card */
        val writeResponse: String get() = Strings.string("home.writeResponse")
        object Empty {
            /** Write your first card */
            val title: String get() = Strings.string("home.empty.title")
            /** Once published, it can appear in the latest public feed. */
            val subtitle: String get() = Strings.string("home.empty.subtitle")
            /** Start writing */
            val cta: String get() = Strings.string("home.empty.cta")
        }
        /** because of “{reason}” */
        fun matchReason(reason: String): String = Strings.format("home.matchReason", mapOf("reason" to reason))
        object Recommended {
            /** The insights you write decide which stories find you. */
            val hint: String get() = Strings.string("home.recommended.hint")
            /** Today's picks are ready */
            val ready: String get() = Strings.string("home.recommended.ready")
        }
        object ColdStart {
            /** Your first card becomes the point this world starts arranging itself around. */
            val title: String get() = Strings.string("home.coldStart.title")
            /** Write a story */
            val cta: String get() = Strings.string("home.coldStart.cta")
        }
    }
    object Card {
        /** Resonate */
        val resonate: String get() = Strings.string("card.resonate")
        /** Resonated */
        val resonated: String get() = Strings.string("card.resonated")
        /** Edit */
        val modify: String get() = Strings.string("card.modify")
        /** Publish */
        val publishResonance: String get() = Strings.string("card.publishResonance")
        /** Save draft */
        val saveResonanceDraft: String get() = Strings.string("card.saveResonanceDraft")
        /** Cards linked to this */
        val linkedCards: String get() = Strings.string("card.linkedCards")
        /** Resonated by */
        val resonatedBy: String get() = Strings.string("card.resonatedBy")
        /** View all */
        val viewAllResonators: String get() = Strings.string("card.viewAllResonators")
        /** No one has resonated with this card yet. */
        val noResonatorsYet: String get() = Strings.string("card.noResonatorsYet")
        /** No bio yet. */
        val noBio: String get() = Strings.string("card.noBio")
        object Resonance {
            /** Reflections on \"{title}\" */
            fun titlePrefill(title: String): String = Strings.format("card.resonance.titlePrefill", mapOf("title" to title))
            /** Your response becomes a card of your own. */
            val hint: String get() = Strings.string("card.resonance.hint")
            /** Not ready to go public? Send it to the author as a note instead. */
            val downgrade: String get() = Strings.string("card.resonance.downgrade")
            /** The insight of this card is \"{coreInsight}\". Have you lived something similar — or the exact opposite? */
            fun aiPrompt(coreInsight: String): String = Strings.format("card.resonance.aiPrompt", mapOf("coreInsight" to coreInsight))
        }
        object Note {
            /** Send the author a little note */
            val entry: String get() = Strings.string("card.note.entry")
            /** A little note */
            val label: String get() = Strings.string("card.note.label")
            /** Something you want to tell the author… */
            val placeholder: String get() = Strings.string("card.note.placeholder")
            /** Only the author can see this. */
            val hint: String get() = Strings.string("card.note.hint")
            /** Want to turn this into a resonance card? */
            val upgrade: String get() = Strings.string("card.note.upgrade")
            /** Your note is on its way. */
            val sent: String get() = Strings.string("card.note.sent")
            /** Send */
            val send: String get() = Strings.string("card.note.send")
            /** Cancel */
            val cancel: String get() = Strings.string("card.note.cancel")
            /** Close */
            val close: String get() = Strings.string("card.note.close")
        }
        object Bookmark {
            /** Saved */
            val saved: String get() = Strings.string("card.bookmark.saved")
            /** Bookmark */
            val add: String get() = Strings.string("card.bookmark.add")
            /** Remove bookmark */
            val remove: String get() = Strings.string("card.bookmark.remove")
        }
        object ResonanceSection {
            /** Cards resonating with this */
            val title: String get() = Strings.string("card.resonanceSection.title")
            /** Resonating with */
            val sourceTitle: String get() = Strings.string("card.resonanceSection.sourceTitle")
            /** No one has resonated with this card yet — be the first. */
            val empty: String get() = Strings.string("card.resonanceSection.empty")
        }
        object LinkModal {
            /** Link with a card */
            val title: String get() = Strings.string("card.linkModal.title")
            /** Pick one of your cards to link with this one. */
            val pickCard: String get() = Strings.string("card.linkModal.pickCard")
            /** Create link */
            val confirm: String get() = Strings.string("card.linkModal.confirm")
            /** Cancel */
            val cancel: String get() = Strings.string("card.linkModal.cancel")
            /** Close */
            val close: String get() = Strings.string("card.linkModal.close")
            /** Linked! */
            val linked: String get() = Strings.string("card.linkModal.linked")
            /** You have no published cards to link yet. */
            val noCards: String get() = Strings.string("card.linkModal.noCards")
        }
        object ResonatorsModal {
            /** Resonated with this card */
            val title: String get() = Strings.string("card.resonatorsModal.title")
        }
        /** Translate to */
        val translateTo: String get() = Strings.string("card.translateTo")
        /** Show original */
        val showOriginal: String get() = Strings.string("card.showOriginal")
        /** Extended cards */
        val related: String get() = Strings.string("card.related")
        /** Contents */
        val toc: String get() = Strings.string("card.toc")
        object AuthorMetrics {
            /** Only you see this */
            val title: String get() = Strings.string("card.authorMetrics.title")
            /** Reads */
            val reads: String get() = Strings.string("card.authorMetrics.reads")
            /** Resonances */
            val resonances: String get() = Strings.string("card.authorMetrics.resonances")
            /** Invites */
            val inviteRequests: String get() = Strings.string("card.authorMetrics.inviteRequests")
        }
        /** Verified */
        val verified: String get() = Strings.string("card.verified")
        /** Private */
        val private: String get() = Strings.string("card.private")
        /** Connections only */
        val connections: String get() = Strings.string("card.connections")
        object NotFound {
            /** This card can't be found */
            val title: String get() = Strings.string("card.notFound.title")
            /** Back to home */
            val back: String get() = Strings.string("card.notFound.back")
        }
        /** Anonymous */
        val anonymousAuthor: String get() = Strings.string("card.anonymousAuthor")
        /** This card was published anonymously — your pen name isn't shown on it or on your profile. */
        val anonymousOwnerNote: String get() = Strings.string("card.anonymousOwnerNote")
    }
    object Messages {
        /** Messages */
        val title: String get() = Strings.string("messages.title")
        /** Quiet conversations with the people you're connected with. */
        val subtitle: String get() = Strings.string("messages.subtitle")
        /** Once you form a connection, your conversations will live here. */
        val empty: String get() = Strings.string("messages.empty")
        /** Connected — no conversation yet */
        val startSection: String get() = Strings.string("messages.startSection")
        /** Pick a conversation from the left. */
        val pickOne: String get() = Strings.string("messages.pickOne")
        /** No messages yet — say hello. */
        val noMessagesYet: String get() = Strings.string("messages.noMessagesYet")
        /** Write a message… */
        val placeholder: String get() = Strings.string("messages.placeholder")
        /** Send */
        val send: String get() = Strings.string("messages.send")
        /** Couldn't send — please try again. */
        val sendError: String get() = Strings.string("messages.sendError")
        /** You can only message people you're connected with. */
        val notConnected: String get() = Strings.string("messages.notConnected")
        /** View profile */
        val viewProfile: String get() = Strings.string("messages.viewProfile")
        /** All conversations */
        val back: String get() = Strings.string("messages.back")
        /** You:  */
        val youPrefix: String get() = Strings.string("messages.youPrefix")
        /** This person doesn't exist. */
        val userNotFound: String get() = Strings.string("messages.userNotFound")
        /** Conversation with {handle} */
        fun threadWith(handle: String): String = Strings.format("messages.threadWith", mapOf("handle" to handle))
        /** Message */
        val messageLink: String get() = Strings.string("messages.messageLink")
        /** Start chatting */
        val startChat: String get() = Strings.string("messages.startChat")
        /** Reply */
        val replyToNote: String get() = Strings.string("messages.replyToNote")
        /** In reply to your note */
        val quotedNote: String get() = Strings.string("messages.quotedNote")
        /** Attach a card */
        val attachCard: String get() = Strings.string("messages.attachCard")
        /** Remove card */
        val removeCard: String get() = Strings.string("messages.removeCard")
        /** Shared a card */
        val cardShared: String get() = Strings.string("messages.cardShared")
        /** Share one of your cards */
        val pickCard: String get() = Strings.string("messages.pickCard")
        /** Share one of your published cards in this conversation. */
        val pickCardSubtitle: String get() = Strings.string("messages.pickCardSubtitle")
        /** Conversation options */
        val moreMenu: String get() = Strings.string("messages.moreMenu")
        /** Search messages */
        val menuSearch: String get() = Strings.string("messages.menuSearch")
        /** Cards & links */
        val menuMedia: String get() = Strings.string("messages.menuMedia")
        /** Delete conversation */
        val menuDelete: String get() = Strings.string("messages.menuDelete")
        /** Search this conversation… */
        val searchPlaceholder: String get() = Strings.string("messages.searchPlaceholder")
        /** {count, plural, =0 {No matches} one {# match} other {# matches}} */
        fun searchCount(count: Int): String = Strings.format("messages.searchCount", mapOf("count" to count))
        /** Close search */
        val searchClose: String get() = Strings.string("messages.searchClose")
        /** Cards & links */
        val mediaTitle: String get() = Strings.string("messages.mediaTitle")
        /** Everything shared in this conversation. */
        val mediaSubtitle: String get() = Strings.string("messages.mediaSubtitle")
        /** Shared cards */
        val mediaCards: String get() = Strings.string("messages.mediaCards")
        /** Links */
        val mediaLinks: String get() = Strings.string("messages.mediaLinks")
        /** Nothing shared here yet. */
        val mediaEmpty: String get() = Strings.string("messages.mediaEmpty")
        /** Delete this conversation? */
        val deleteConfirmTitle: String get() = Strings.string("messages.deleteConfirmTitle")
        /** This removes the whole conversation for both of you. It can’t be undone. */
        val deleteConfirmBody: String get() = Strings.string("messages.deleteConfirmBody")
        /** Keep it */
        val deleteCancel: String get() = Strings.string("messages.deleteCancel")
        /** Delete */
        val deleteConfirm: String get() = Strings.string("messages.deleteConfirm")
        /** Couldn’t delete — please try again. */
        val deleteError: String get() = Strings.string("messages.deleteError")
    }
    object Write {
        /** Give it a one-line title first. */
        val titleRequired: String get() = Strings.string("write.titleRequired")
        /** New card */
        val title: String get() = Strings.string("write.title")
        /** Edit draft */
        val editTitle: String get() = Strings.string("write.editTitle")
        /** Edit a published card */
        val editPublishedTitle: String get() = Strings.string("write.editPublishedTitle")
        /** Close editor */
        val closeEditor: String get() = Strings.string("write.closeEditor")
        /** Drag to resize panes */
        val resizeDivider: String get() = Strings.string("write.resizeDivider")
        /** Original Article */
        val referenceCard: String get() = Strings.string("write.referenceCard")
        /** One-line title */
        val coreLabel: String get() = Strings.string("write.coreLabel")
        /** e.g. Being seen matters more than being liked. */
        val corePlaceholder: String get() = Strings.string("write.corePlaceholder")
        /** Story */
        val storyLabel: String get() = Strings.string("write.storyLabel")
        /** Write the moment that pulled that line out of you… */
        val storyPlaceholder: String get() = Strings.string("write.storyPlaceholder")
        object Editor {
            /** Editor toolbar */
            val toolbarLabel: String get() = Strings.string("write.editor.toolbarLabel")
            /** Bold */
            val bold: String get() = Strings.string("write.editor.bold")
            /** Italic */
            val italic: String get() = Strings.string("write.editor.italic")
            /** Heading 2 */
            val h2: String get() = Strings.string("write.editor.h2")
            /** Heading 3 */
            val h3: String get() = Strings.string("write.editor.h3")
            /** List */
            val bulletList: String get() = Strings.string("write.editor.bulletList")
            /** Numbered */
            val orderedList: String get() = Strings.string("write.editor.orderedList")
            /** Quote */
            val quote: String get() = Strings.string("write.editor.quote")
            /** Insert card */
            val insertCard: String get() = Strings.string("write.editor.insertCard")
            /** Insert image */
            val insertImage: String get() = Strings.string("write.editor.insertImage")
            /** Uploading image… */
            val imageUploading: String get() = Strings.string("write.editor.imageUploading")
            /** Image upload failed. Please try again. */
            val imageUploadError: String get() = Strings.string("write.editor.imageUploadError")
            /** Remove image */
            val removeImage: String get() = Strings.string("write.editor.removeImage")
            /** Remove card */
            val removeCard: String get() = Strings.string("write.editor.removeCard")
            object CardModal {
                /** Insert a card link */
                val title: String get() = Strings.string("write.editor.cardModal.title")
                /** Pick one of your public cards — the link lands at your cursor. */
                val subtitle: String get() = Strings.string("write.editor.cardModal.subtitle")
                /** You have no public cards yet. */
                val empty: String get() = Strings.string("write.editor.cardModal.empty")
                /** Cancel */
                val cancel: String get() = Strings.string("write.editor.cardModal.cancel")
            }
        }
        /** Tags */
        val tagsLabel: String get() = Strings.string("write.tagsLabel")
        /** AI: suggest 2–3 */
        val tagsSuggest: String get() = Strings.string("write.tagsSuggest")
        /** Thinking… */
        val tagsSuggesting: String get() = Strings.string("write.tagsSuggesting")
        /** Couldn’t suggest tags. Please try again. */
        val tagsSuggestError: String get() = Strings.string("write.tagsSuggestError")
        /** Type a tag… */
        val tagsPlaceholder: String get() = Strings.string("write.tagsPlaceholder")
        /** Add */
        val tagsAdd: String get() = Strings.string("write.tagsAdd")
        /** Image (optional) */
        val mediaLabel: String get() = Strings.string("write.mediaLabel")
        /** Remove image */
        val mediaRemove: String get() = Strings.string("write.mediaRemove")
        /** Click, or drag an image here */
        val mediaPlaceholder: String get() = Strings.string("write.mediaPlaceholder")
        /** PNG, JPG, WebP · up to 5MB */
        val mediaHint: String get() = Strings.string("write.mediaHint")
        /** Image upload failed. Please try again. */
        val mediaUploadError: String get() = Strings.string("write.mediaUploadError")
        /** Sketching it in… */
        val mediaUploading: String get() = Strings.string("write.mediaUploading")
        /** Generate */
        val mediaGenerate: String get() = Strings.string("write.mediaGenerate")
        /** An image from your story */
        val mediaGenerateHint: String get() = Strings.string("write.mediaGenerateHint")
        /** Write your story first */
        val mediaGenerateNeedStory: String get() = Strings.string("write.mediaGenerateNeedStory")
        /** Imagining a scene… */
        val mediaGenerating: String get() = Strings.string("write.mediaGenerating")
        /** Couldn’t generate an image. Please try again. */
        val mediaGenerateError: String get() = Strings.string("write.mediaGenerateError")
        /** AI-generated illustration */
        val mediaGeneratedLabel: String get() = Strings.string("write.mediaGeneratedLabel")
        object Visibility {
            /** Who can see */
            val label: String get() = Strings.string("write.visibility.label")
            /** Public */
            val public: String get() = Strings.string("write.visibility.public")
            /** Connections only */
            val connections: String get() = Strings.string("write.visibility.connections")
            /** Only me */
            val private: String get() = Strings.string("write.visibility.private")
        }
        object Ai {
            /** AI writing partner */
            val panel: String get() = Strings.string("write.ai.panel")
            /** Polish */
            val polish: String get() = Strings.string("write.ai.polish")
            /** Keep your voice, just smooth the prose */
            val polishHint: String get() = Strings.string("write.ai.polishHint")
            /** Title ideas */
            val title: String get() = Strings.string("write.ai.title")
            /** 3 candidates for the core thought */
            val titleHint: String get() = Strings.string("write.ai.titleHint")
            /** Generate tags */
            val tags: String get() = Strings.string("write.ai.tags")
            /** Concepts, not keywords */
            val tagsHint: String get() = Strings.string("write.ai.tagsHint")
            /** Use */
            val apply: String get() = Strings.string("write.ai.apply")
            /** Keep mine */
            val keep: String get() = Strings.string("write.ai.keep")
            /** Try again */
            val regenerate: String get() = Strings.string("write.ai.regenerate")
            /** (MVP AI is a stub; real model in Phase 3) */
            val stubNotice: String get() = Strings.string("write.ai.stubNotice")
        }
        /** Publish */
        val publish: String get() = Strings.string("write.publish")
        /** Publishing… */
        val publishing: String get() = Strings.string("write.publishing")
        /** Draft saved · {time} */
        fun autosaved(time: String): String = Strings.format("write.autosaved", mapOf("time" to time))
        /** Drafts save themselves — you can leave any time. */
        val autosaveHint: String get() = Strings.string("write.autosaveHint")
        /** This card is already published. Changes are kept privately until you press Save changes. */
        val editLiveHint: String get() = Strings.string("write.editLiveHint")
        /** Changes saved privately · {time} (readers still see the old version) */
        fun editBuffered(time: String): String = Strings.format("write.editBuffered", mapOf("time" to time))
        /** You have unsaved changes here — only you can see them. */
        val editBufferedIdle: String get() = Strings.string("write.editBufferedIdle")
        /** Save draft and leave */
        val saveDraftAndLeave: String get() = Strings.string("write.saveDraftAndLeave")
        /** Save changes */
        val saveChanges: String get() = Strings.string("write.saveChanges")
        /** Saving… */
        val saving: String get() = Strings.string("write.saving")
        /** Discard changes */
        val discardChanges: String get() = Strings.string("write.discardChanges")
        object PublishPanel {
            /** Publish this card */
            val title: String get() = Strings.string("write.publishPanel.title")
            /** Reading your story… */
            val insightLoading: String get() = Strings.string("write.publishPanel.insightLoading")
            /** What you seem to be saying — “{coreInsight}” */
            fun insight(coreInsight: String): String = Strings.format("write.publishPanel.insight", mapOf("coreInsight" to coreInsight))
            /** Publish anonymously */
            val anonymousToggle: String get() = Strings.string("write.publishPanel.anonymousToggle")
            /** Anonymous */
            val anonymousName: String get() = Strings.string("write.publishPanel.anonymousName")
            /** Anonymous cards never appear on your profile. */
            val anonymousHint: String get() = Strings.string("write.publishPanel.anonymousHint")
            /** Publish */
            val publish: String get() = Strings.string("write.publishPanel.publish")
            /** Publishing… */
            val publishing: String get() = Strings.string("write.publishPanel.publishing")
            /** Not yet */
            val cancel: String get() = Strings.string("write.publishPanel.cancel")
            /** Update this card */
            val updateTitle: String get() = Strings.string("write.publishPanel.updateTitle")
            /** After this, readers see this version. The publish date stays as it was. */
            val updateHint: String get() = Strings.string("write.publishPanel.updateHint")
            /** Save changes */
            val update: String get() = Strings.string("write.publishPanel.update")
            /** Saving… */
            val updating: String get() = Strings.string("write.publishPanel.updating")
        }
        object FirstCard {
            /** Write your first card */
            val title: String get() = Strings.string("write.firstCard.title")
            /** Not sure where to start? Pick a question and write what surfaces. */
            val intro: String get() = Strings.string("write.firstCard.intro")
            /** What small moment recently changed how you see something? */
            val q1: String get() = Strings.string("write.firstCard.q1")
            /** What is one thing you wish you could tell your past self? */
            val q2: String get() = Strings.string("write.firstCard.q2")
            /** Which failure taught you something nobody else ever did? */
            val q3: String get() = Strings.string("write.firstCard.q3")
        }
    }
    object Me {
        /** Joined {date} */
        fun joined(date: String): String = Strings.format("me.joined", mapOf("date" to date))
        /** Edit profile */
        val editProfile: String get() = Strings.string("me.editProfile")
        /** View public profile */
        val viewPublicProfile: String get() = Strings.string("me.viewPublicProfile")
        /** No bio yet. */
        val bioEmpty: String get() = Strings.string("me.bioEmpty")
        object Tabs {
            /** Published */
            val published: String get() = Strings.string("me.tabs.published")
            /** Private */
            val private: String get() = Strings.string("me.tabs.private")
            /** Drafts */
            val draft: String get() = Strings.string("me.tabs.draft")
            /** Resonated */
            val resonated: String get() = Strings.string("me.tabs.resonated")
            /** Linked */
            val linked: String get() = Strings.string("me.tabs.linked")
            /** Bookmarks */
            val bookmarks: String get() = Strings.string("me.tabs.bookmarks")
            /** Thought map */
            val thoughtMap: String get() = Strings.string("me.tabs.thoughtMap")
        }
        object ThoughtMap {
            /** Bring your cards onto the map and start weaving your thoughts together. */
            val empty: String get() = Strings.string("me.thoughtMap.empty")
            /** Add card */
            val addCard: String get() = Strings.string("me.thoughtMap.addCard")
            /** Card */
            val addCardShort: String get() = Strings.string("me.thoughtMap.addCardShort")
            /** New group */
            val addGroup: String get() = Strings.string("me.thoughtMap.addGroup")
            /** Group */
            val addGroupShort: String get() = Strings.string("me.thoughtMap.addGroupShort")
            /** Untitled group */
            val newGroup: String get() = Strings.string("me.thoughtMap.newGroup")
            /** Pick a card to add */
            val trayTitle: String get() = Strings.string("me.thoughtMap.trayTitle")
            /** Every card is already on the map. */
            val trayEmpty: String get() = Strings.string("me.thoughtMap.trayEmpty")
            /** Zoom in */
            val zoomIn: String get() = Strings.string("me.thoughtMap.zoomIn")
            /** Zoom out */
            val zoomOut: String get() = Strings.string("me.thoughtMap.zoomOut")
            /** Fit to view */
            val zoomFit: String get() = Strings.string("me.thoughtMap.zoomFit")
            /** Open */
            val open: String get() = Strings.string("me.thoughtMap.open")
            /** Remove from map */
            val removeFromMap: String get() = Strings.string("me.thoughtMap.removeFromMap")
            /** Delete connection */
            val deleteEdge: String get() = Strings.string("me.thoughtMap.deleteEdge")
            /** Delete group */
            val deleteGroup: String get() = Strings.string("me.thoughtMap.deleteGroup")
            /** What does this connection mean? */
            val edgeLabelPlaceholder: String get() = Strings.string("me.thoughtMap.edgeLabelPlaceholder")
            /** Name this group */
            val groupTitlePlaceholder: String get() = Strings.string("me.thoughtMap.groupTitlePlaceholder")
            /** Draw a connection */
            val linkHandle: String get() = Strings.string("me.thoughtMap.linkHandle")
            /** Resize group */
            val resizeGroup: String get() = Strings.string("me.thoughtMap.resizeGroup")
            /** Back to profile */
            val back: String get() = Strings.string("me.thoughtMap.back")
            /** Leave */
            val leave: String get() = Strings.string("me.thoughtMap.leave")
        }
        /** Your first card becomes the point this world starts arranging itself around. */
        val emptyPublished: String get() = Strings.string("me.emptyPublished")
        /** No private cards. */
        val emptyPrivate: String get() = Strings.string("me.emptyPrivate")
        /** No drafts. */
        val emptyDraft: String get() = Strings.string("me.emptyDraft")
        /** No one has linked a card to you yet. */
        val emptyLinked: String get() = Strings.string("me.emptyLinked")
        /** No resonances yet. */
        val emptyResonated: String get() = Strings.string("me.emptyResonated")
        /** When a story is too good to forget, press the bookmark — it will wait here quietly, only for you. */
        val emptyBookmarks: String get() = Strings.string("me.emptyBookmarks")
        object Actions {
            /** Manage card */
            val menuLabel: String get() = Strings.string("me.actions.menuLabel")
            /** Edit */
            val edit: String get() = Strings.string("me.actions.edit")
            /** Make public */
            val makePublic: String get() = Strings.string("me.actions.makePublic")
            /** Make private */
            val makePrivate: String get() = Strings.string("me.actions.makePrivate")
            /** Delete */
            val delete: String get() = Strings.string("me.actions.delete")
            /** Delete this card? */
            val deleteConfirmTitle: String get() = Strings.string("me.actions.deleteConfirmTitle")
            /** This cannot be undone — the story and its resonance links will be gone. */
            val deleteConfirmBody: String get() = Strings.string("me.actions.deleteConfirmBody")
            /** Delete card */
            val deleteConfirm: String get() = Strings.string("me.actions.deleteConfirm")
            /** Keep it */
            val deleteCancel: String get() = Strings.string("me.actions.deleteCancel")
        }
        /** Anonymous */
        val anonymousBadge: String get() = Strings.string("me.anonymousBadge")
        /** Write a story */
        val emptyPublishedCta: String get() = Strings.string("me.emptyPublishedCta")
        /** Show */
        val filterLabel: String get() = Strings.string("me.filterLabel")
    }
    object Profile {
        /** Not connected */
        val notConnected: String get() = Strings.string("profile.notConnected")
        /** Connected */
        val connected: String get() = Strings.string("profile.connected")
        /** Message */
        val message: String get() = Strings.string("profile.message")
        /** More cards, saved for those who connect ✿ */
        val softLock: String get() = Strings.string("profile.softLock")
        /** Cards linked to them */
        val linkedCards: String get() = Strings.string("profile.linkedCards")
        /** ⋯ */
        val more: String get() = Strings.string("profile.more")
        /** Report */
        val report: String get() = Strings.string("profile.report")
        /** Block */
        val block: String get() = Strings.string("profile.block")
        /** Disconnect */
        val disconnect: String get() = Strings.string("profile.disconnect")
        /** Translating… */
        val translating: String get() = Strings.string("profile.translating")
        /** Show original */
        val showOriginal: String get() = Strings.string("profile.showOriginal")
        /** This person can't be found */
        val notFound: String get() = Strings.string("profile.notFound")
        /** Back to home */
        val backHome: String get() = Strings.string("profile.backHome")
        /** {handle} · Resonance */
        fun shareTitle(handle: String): String = Strings.format("profile.shareTitle", mapOf("handle" to handle))
        /** {handle}'s life stories on Resonance */
        fun shareDescription(handle: String): String = Strings.format("profile.shareDescription", mapOf("handle" to handle))
        /** No bio yet. */
        val bioEmpty: String get() = Strings.string("profile.bioEmpty")
        /** Joined {date} */
        fun joined(date: String): String = Strings.format("profile.joined", mapOf("date" to date))
        /** Edit profile */
        val editProfile: String get() = Strings.string("profile.editProfile")
        /** {count, plural, =0 {No public cards} one {# public card} other {# public cards}} */
        fun cardCount(count: Int): String = Strings.format("profile.cardCount", mapOf("count" to count))
        /** Published */
        val publishedHeading: String get() = Strings.string("profile.publishedHeading")
        /** Nothing published yet. */
        val emptyPublished: String get() = Strings.string("profile.emptyPublished")
        /** Your first card becomes the point this world starts arranging itself around. */
        val emptyPublishedSelf: String get() = Strings.string("profile.emptyPublishedSelf")
        /** Write a story */
        val emptyPublishedCta: String get() = Strings.string("profile.emptyPublishedCta")
    }
    object Invite {
        /** Invite to connect */
        val title: String get() = Strings.string("invite.title")
        /** Reference a card (optional) */
        val referenceCard: String get() = Strings.string("invite.referenceCard")
        /** None */
        val noReference: String get() = Strings.string("invite.noReference")
        /** Say one thing (required, 14–140 chars) */
        val messageLabel: String get() = Strings.string("invite.messageLabel")
        /** Let them know why you want to connect… */
        val messagePlaceholder: String get() = Strings.string("invite.messagePlaceholder")
        /** {n} invites left today */
        fun quota(n: Int): String = Strings.format("invite.quota", mapOf("n" to n))
        /** Daily invite quota used up. Try tomorrow. */
        val quotaFull: String get() = Strings.string("invite.quotaFull")
        /** Send invite */
        val send: String get() = Strings.string("invite.send")
        /** Cancel */
        val cancel: String get() = Strings.string("invite.cancel")
        /** Waiting for their response */
        val sent: String get() = Strings.string("invite.sent")
        /** {handle} wants to connect */
        fun receivedTitle(handle: String): String = Strings.format("invite.receivedTitle", mapOf("handle" to handle))
        /** Accept */
        val accept: String get() = Strings.string("invite.accept")
        /** Later */
        val later: String get() = Strings.string("invite.later")
        /** See who */
        val seeWho: String get() = Strings.string("invite.seeWho")
        /** You’re connected ✿ */
        val successTitle: String get() = Strings.string("invite.successTitle")
        /** You can now see each other’s full card box and DM. */
        val successSubtitle: String get() = Strings.string("invite.successSubtitle")
        /** {days} days to respond */
        fun expiresIn(days: Int): String = Strings.format("invite.expiresIn", mapOf("days" to days))
    }
    object InviteInbox {
        /** {count} pending connection invite(s) */
        fun title(count: Int): String = Strings.format("inviteInbox.title", mapOf("count" to count))
        /** Accept */
        val accept: String get() = Strings.string("inviteInbox.accept")
        /** Decline */
        val decline: String get() = Strings.string("inviteInbox.decline")
        /** respond by {date} */
        fun expiresAt(date: String): String = Strings.format("inviteInbox.expiresAt", mapOf("date" to date))
        /** (No message) */
        val emptyMessage: String get() = Strings.string("inviteInbox.emptyMessage")
    }
    object Auth {
        /** Welcome back */
        val signInTitle: String get() = Strings.string("auth.signInTitle")
        /** First visit */
        val signUpTitle: String get() = Strings.string("auth.signUpTitle")
        /** Email */
        val email: String get() = Strings.string("auth.email")
        /** Password */
        val password: String get() = Strings.string("auth.password")
        /** Send me a magic link */
        val magicLink: String get() = Strings.string("auth.magicLink")
        /** Sign in */
        val signIn: String get() = Strings.string("auth.signIn")
        /** Signing in… */
        val signingIn: String get() = Strings.string("auth.signingIn")
        /** Create account */
        val signUp: String get() = Strings.string("auth.signUp")
        /** Creating… */
        val creating: String get() = Strings.string("auth.creating")
        /** Continue with Google */
        val continueWithGoogle: String get() = Strings.string("auth.continueWithGoogle")
        /** Continue with Apple */
        val continueWithApple: String get() = Strings.string("auth.continueWithApple")
        /** We use Google to sign you in. We never see your password. */
        val googleIntro: String get() = Strings.string("auth.googleIntro")
        /** Sign in failed. Please try again. */
        val signInError: String get() = Strings.string("auth.signInError")
        /** Could not create the account. Please try again. */
        val signUpError: String get() = Strings.string("auth.signUpError")
        /** No account yet? */
        val switchToSignUp: String get() = Strings.string("auth.switchToSignUp")
        /** Already have one? */
        val switchToSignIn: String get() = Strings.string("auth.switchToSignIn")
        /** Step {current} / {total} */
        fun step(current: Int, total: Int): String = Strings.format("auth.step", mapOf("current" to current, "total" to total))
        /** Email */
        val stepEmail: String get() = Strings.string("auth.stepEmail")
        /** Verify phone */
        val stepPhone: String get() = Strings.string("auth.stepPhone")
        /** Pick a handle */
        val stepHandle: String get() = Strings.string("auth.stepHandle")
        /** Phone number */
        val phoneLabel: String get() = Strings.string("auth.phoneLabel")
        /** We use it to check you’re a real person. Never shown publicly. */
        val phoneHint: String get() = Strings.string("auth.phoneHint")
        /** SMS code */
        val otpLabel: String get() = Strings.string("auth.otpLabel")
        /** Send code */
        val otpSend: String get() = Strings.string("auth.otpSend")
        /** Resend */
        val otpResend: String get() = Strings.string("auth.otpResend")
        /** Handle (2–20 chars) */
        val handleLabel: String get() = Strings.string("auth.handleLabel")
        /** Available ✿ */
        val handleAvailable: String get() = Strings.string("auth.handleAvailable")
        /** Taken */
        val handleTaken: String get() = Strings.string("auth.handleTaken")
        /** Checking… */
        val handleChecking: String get() = Strings.string("auth.handleChecking")
        /** Where are you? */
        val regionLabel: String get() = Strings.string("auth.regionLabel")
        /** Your main language */
        val primaryLocaleLabel: String get() = Strings.string("auth.primaryLocaleLabel")
        /** Auto-translate my cards to: */
        val autoTranslateLabel: String get() = Strings.string("auth.autoTranslateLabel")
        /** Next */
        val next: String get() = Strings.string("auth.next")
        /** Back */
        val back: String get() = Strings.string("auth.back")
        /** Finish */
        val finish: String get() = Strings.string("auth.finish")
        /** Welcome, {handle}. Start with your first card. */
        fun welcome(handle: String): String = Strings.format("auth.welcome", mapOf("handle" to handle))
        /** Your account is scheduled for deletion. Sign in within 7 days to cancel. */
        val deletionScheduled: String get() = Strings.string("auth.deletionScheduled")
        /** By continuing, you agree to the {terms} and the {privacy}. */
        fun agreeTerms(terms: String, privacy: String): String = Strings.format("auth.agreeTerms", mapOf("terms" to terms, "privacy" to privacy))
        /** Terms of Use */
        val termsLink: String get() = Strings.string("auth.termsLink")
        /** Privacy Policy */
        val privacyLink: String get() = Strings.string("auth.privacyLink")
    }
    object Settings {
        /** Settings */
        val title: String get() = Strings.string("settings.title")
        object Sections {
            /** Profile */
            val profile: String get() = Strings.string("settings.sections.profile")
            /** Account */
            val account: String get() = Strings.string("settings.sections.account")
            /** Privacy & connections */
            val privacy: String get() = Strings.string("settings.sections.privacy")
            /** Notifications */
            val notifications: String get() = Strings.string("settings.sections.notifications")
            /** Language */
            val language: String get() = Strings.string("settings.sections.language")
            /** Appearance */
            val appearance: String get() = Strings.string("settings.sections.appearance")
            /** AI writing partner */
            val ai: String get() = Strings.string("settings.sections.ai")
            /** Terms */
            val terms: String get() = Strings.string("settings.sections.terms")
            /** Delete account */
            val delete: String get() = Strings.string("settings.sections.delete")
        }
        object Profile {
            /** Handle */
            val handle: String get() = Strings.string("settings.profile.handle")
            /** One-line bio (≤ 80 chars) */
            val bio: String get() = Strings.string("settings.profile.bio")
            /** Region */
            val region: String get() = Strings.string("settings.profile.region")
            /** Profile photo */
            val avatar: String get() = Strings.string("settings.profile.avatar")
            /** Click or drag an image here · PNG, JPG, WebP */
            val avatarHint: String get() = Strings.string("settings.profile.avatarHint")
            /** Change profile photo */
            val avatarChange: String get() = Strings.string("settings.profile.avatarChange")
            /** Sketching it in… */
            val avatarUploading: String get() = Strings.string("settings.profile.avatarUploading")
            /** Upload failed. Please try again. */
            val avatarError: String get() = Strings.string("settings.profile.avatarError")
        }
        object Account {
            /** Email */
            val email: String get() = Strings.string("settings.account.email")
            /** Phone (verified) */
            val phone: String get() = Strings.string("settings.account.phone")
            /** Password */
            val password: String get() = Strings.string("settings.account.password")
            /** Sign out */
            val signOut: String get() = Strings.string("settings.account.signOut")
        }
        object Privacy {
            /** Default publish scope */
            val defaultVisibility: String get() = Strings.string("settings.privacy.defaultVisibility")
            /** Searchable by handle */
            val searchable: String get() = Strings.string("settings.privacy.searchable")
            /** Let AI learn from my cards */
            val aiOptIn: String get() = Strings.string("settings.privacy.aiOptIn")
            /** Manage blocks */
            val manageBlocks: String get() = Strings.string("settings.privacy.manageBlocks")
        }
        object Notifications {
            /** Daily resonance summary */
            val resonance: String get() = Strings.string("settings.notifications.resonance")
            /** Connection invites */
            val connection: String get() = Strings.string("settings.notifications.connection")
            /** Direct messages */
            val dm: String get() = Strings.string("settings.notifications.dm")
            /** Translation complete */
            val translation: String get() = Strings.string("settings.notifications.translation")
        }
        object Language {
            /** UI language */
            val ui: String get() = Strings.string("settings.language.ui")
            /** Primary writing language */
            val original: String get() = Strings.string("settings.language.original")
            /** Auto-translate my cards */
            val autoTranslate: String get() = Strings.string("settings.language.autoTranslate")
            /** When reading others’ cards */
            val readPreference: String get() = Strings.string("settings.language.readPreference")
        }
        object Ai {
            /** Let AI polish my drafts */
            val polish: String get() = Strings.string("settings.ai.polish")
            /** Let AI generate tags */
            val tags: String get() = Strings.string("settings.ai.tags")
            /** Let AI offer hints on empty cards */
            val hints: String get() = Strings.string("settings.ai.hints")
        }
        object Delete {
            /** Delete account */
            val title: String get() = Strings.string("settings.delete.title")
            /** You'll be signed out right away. After 7 days your account, cards, messages and uploaded images are deleted for good; si */
            val warn: String get() = Strings.string("settings.delete.warn")
            /** Before you go, you can download everything you've written. */
            val exportHint: String get() = Strings.string("settings.delete.exportHint")
            /** Download my data */
            val export: String get() = Strings.string("settings.delete.export")
            /** Preparing… */
            val exporting: String get() = Strings.string("settings.delete.exporting")
            /** Delete account */
            val button: String get() = Strings.string("settings.delete.button")
            /** Delete your account? */
            val confirmTitle: String get() = Strings.string("settings.delete.confirmTitle")
            /** You'll be signed out. After {date}, your account and everything in it are deleted and can't be recovered. */
            fun confirmBody(date: String): String = Strings.format("settings.delete.confirmBody", mapOf("date" to date))
            /** Delete account */
            val confirm: String get() = Strings.string("settings.delete.confirm")
            /** Keep my account */
            val cancel: String get() = Strings.string("settings.delete.cancel")
            /** That didn't go through. Try again. */
            val error: String get() = Strings.string("settings.delete.error")
        }
    }
    object Safety {
        /** More options */
        val menuLabel: String get() = Strings.string("safety.menuLabel")
        /** Report this card */
        val reportCard: String get() = Strings.string("safety.reportCard")
        /** Report this person */
        val reportUser: String get() = Strings.string("safety.reportUser")
        /** Report this conversation */
        val reportMessage: String get() = Strings.string("safety.reportMessage")
        /** Block */
        val block: String get() = Strings.string("safety.block")
        /** Unblock */
        val unblock: String get() = Strings.string("safety.unblock")
        /** Block {handle}? */
        fun blockTitle(handle: String): String = Strings.format("safety.blockTitle", mapOf("handle" to handle))
        /** They won't be able to message you, invite you or send you notes, and your connection will end. You won't see their cards */
        val blockBody: String get() = Strings.string("safety.blockBody")
        /** Block */
        val blockConfirm: String get() = Strings.string("safety.blockConfirm")
        /** Cancel */
        val cancel: String get() = Strings.string("safety.cancel")
        /** That didn't work. Try again. */
        val actionError: String get() = Strings.string("safety.actionError")
        /** this author */
        val anonymousAuthor: String get() = Strings.string("safety.anonymousAuthor")
        /** You blocked {handle} */
        fun blockedNotice(handle: String): String = Strings.format("safety.blockedNotice", mapOf("handle" to handle))
        /** You don't see their cards, and they can't reach you. */
        val blockedNoticeBody: String get() = Strings.string("safety.blockedNoticeBody")
        object Report {
            /** Report this card */
            val titleCard: String get() = Strings.string("safety.report.titleCard")
            /** Report {handle} */
            fun titleUser(handle: String): String = Strings.format("safety.report.titleUser", mapOf("handle" to handle))
            /** Report your conversation with {handle} */
            fun titleMessage(handle: String): String = Strings.format("safety.report.titleMessage", mapOf("handle" to handle))
            /** Tell us what happened. They won't know who reported them. */
            val intro: String get() = Strings.string("safety.report.intro")
            /** Reason */
            val reason: String get() = Strings.string("safety.report.reason")
            object Reasons {
                /** Spam or advertising */
                val spam: String get() = Strings.string("safety.report.reasons.spam")
                /** Harassment or bullying */
                val harassment: String get() = Strings.string("safety.report.reasons.harassment")
                /** Hate speech or discrimination */
                val hate: String get() = Strings.string("safety.report.reasons.hate")
                /** Sexual or explicit content */
                val sexual: String get() = Strings.string("safety.report.reasons.sexual")
                /** Self-harm or suicide */
                val self_harm: String get() = Strings.string("safety.report.reasons.self_harm")
                /** Violence or threats */
                val violence: String get() = Strings.string("safety.report.reasons.violence")
                /** Something else */
                val other: String get() = Strings.string("safety.report.reasons.other")
            }
            /** Details (optional) */
            val detail: String get() = Strings.string("safety.report.detail")
            /** What made you uncomfortable? */
            val detailPlaceholder: String get() = Strings.string("safety.report.detailPlaceholder")
            /** Also block {handle} */
            fun alsoBlock(handle: String): String = Strings.format("safety.report.alsoBlock", mapOf("handle" to handle))
            /** Send report */
            val submit: String get() = Strings.string("safety.report.submit")
            /** Thanks for telling us */
            val doneTitle: String get() = Strings.string("safety.report.doneTitle")
            /** We'll review it as soon as we can. If someone is in immediate danger, contact your local emergency services. */
            val doneBody: String get() = Strings.string("safety.report.doneBody")
            /** You've also blocked {handle}. */
            fun doneBlocked(handle: String): String = Strings.format("safety.report.doneBlocked", mapOf("handle" to handle))
            /** Close */
            val close: String get() = Strings.string("safety.report.close")
        }
        object BlockedList {
            /** Blocked people */
            val title: String get() = Strings.string("safety.blockedList.title")
            /** People you block can't reach you, and you don't see their cards. */
            val subtitle: String get() = Strings.string("safety.blockedList.subtitle")
            /** You haven't blocked anyone. */
            val empty: String get() = Strings.string("safety.blockedList.empty")
            /** Blocked {date} */
            fun since(date: String): String = Strings.format("safety.blockedList.since", mapOf("date" to date))
            /** Deleted account */
            val unknownUser: String get() = Strings.string("safety.blockedList.unknownUser")
            /** Close */
            val close: String get() = Strings.string("safety.blockedList.close")
        }
    }
    object AccountDeletion {
        /** Your account will be deleted on {date}. */
        fun banner(date: String): String = Strings.format("accountDeletion.banner", mapOf("date" to date))
        /** Cancel deletion */
        val cancel: String get() = Strings.string("accountDeletion.cancel")
        /** Couldn't cancel. Try again. */
        val error: String get() = Strings.string("accountDeletion.error")
    }
    object Native {
        /** Couldn't load this — please try again. */
        val loadError: String get() = Strings.string("native.loadError")
        /** Copy */
        val copy: String get() = Strings.string("native.copy")
        /** Couldn't save that — try again. */
        val saveError: String get() = Strings.string("native.saveError")
        /** Try again */
        val retry: String get() = Strings.string("native.retry")
        /** You're offline. What you've already opened is still here. */
        val offline: String get() = Strings.string("native.offline")
        /** Feed */
        val tabFeed: String get() = Strings.string("native.tabFeed")
    }
}
