// Generated by scripts/apps/l10n.ts from src/messages — do not edit.
// The strings themselves are read at runtime from the bundled catalogs.
// swiftlint:disable all

public enum L10n {
    public enum Metadata {
        /// Resonance — Let lives influence lives
        public static var title: String { Strings.shared.string("metadata.title") }
        /// A space for real life stories from around the world to connect.
        public static var description: String { Strings.shared.string("metadata.description") }
    }
    public enum Nav {
        /// About
        public static var about: String { Strings.shared.string("nav.about") }
        /// Explore
        public static var explore: String { Strings.shared.string("nav.explore") }
        /// Stories
        public static var stories: String { Strings.shared.string("nav.stories") }
        /// Sign In
        public static var signIn: String { Strings.shared.string("nav.signIn") }
        /// 中
        public static var languageSwitch: String { Strings.shared.string("nav.languageSwitch") }
        /// Open menu
        public static var openMenu: String { Strings.shared.string("nav.openMenu") }
        /// Site navigation
        public static var siteNav: String { Strings.shared.string("nav.siteNav") }
    }
    public enum Hero {
        /// ✦ Real life stories
        public static var tag: String { Strings.shared.string("hero.tag") }
        /// Let lives 
        public static var headlinePrefix: String { Strings.shared.string("hero.headlinePrefix") }
        /// influence
        public static var headlineAccent: String { Strings.shared.string("hero.headlineAccent") }
        ///  lives
        public static var headlineSuffix: String { Strings.shared.string("hero.headlineSuffix") }
        /// A space for real life stories from around the world to connect. Read, share, and resonate with the experiences that shap
        public static var description: String { Strings.shared.string("hero.description") }
        /// Explore stories
        public static var explore: String { Strings.shared.string("hero.explore") }
        /// Share your story
        public static var share: String { Strings.shared.string("hero.share") }
        /// Be among the first storytellers here
        public static var proof: String { Strings.shared.string("hero.proof") }
    }
    public enum Feed {
        /// Latest stories
        public static var tag: String { Strings.shared.string("feed.tag") }
        /// Stories worth reading
        public static var title: String { Strings.shared.string("feed.title") }
        /// Real people, real experiences — every voice carries a world.
        public static var subtitle: String { Strings.shared.string("feed.subtitle") }
        /// View all stories
        public static var viewAll: String { Strings.shared.string("feed.viewAll") }
    }
    public enum Cta {
        /// Share your story and let the world hear your voice
        public static var title: String { Strings.shared.string("cta.title") }
        /// Every story matters. Yours might be the one that changes someone’s day.
        public static var description: String { Strings.shared.string("cta.description") }
        /// Start sharing
        public static var start: String { Strings.shared.string("cta.start") }
        /// Create a story
        public static var create: String { Strings.shared.string("cta.create") }
    }
    public enum Footer {
        /// Let lives influence lives
        public static var tagline: String { Strings.shared.string("footer.tagline") }
        /// About
        public static var about: String { Strings.shared.string("footer.about") }
        /// Contact
        public static var contact: String { Strings.shared.string("footer.contact") }
        /// Privacy
        public static var privacy: String { Strings.shared.string("footer.privacy") }
        /// Terms
        public static var terms: String { Strings.shared.string("footer.terms") }
        /// © 2026 Resonance. All rights reserved.
        public static var copyright: String { Strings.shared.string("footer.copyright") }
    }
    public enum Tweaks {
        /// Tweaks
        public static var title: String { Strings.shared.string("tweaks.title") }
        /// Open tweaks panel
        public static var `open`: String { Strings.shared.string("tweaks.open") }
        /// Close tweaks panel
        public static var close: String { Strings.shared.string("tweaks.close") }
        /// Accent color
        public static var accentColor: String { Strings.shared.string("tweaks.accentColor") }
        /// Terracotta (default)
        public static var accentTerracotta: String { Strings.shared.string("tweaks.accentTerracotta") }
        /// Sage
        public static var accentSage: String { Strings.shared.string("tweaks.accentSage") }
        /// Lavender
        public static var accentLavender: String { Strings.shared.string("tweaks.accentLavender") }
        /// Yellow
        public static var accentYellow: String { Strings.shared.string("tweaks.accentYellow") }
        /// Heading font
        public static var fontFamily: String { Strings.shared.string("tweaks.fontFamily") }
        /// Playfair Display (default)
        public static var fontDefault: String { Strings.shared.string("tweaks.fontDefault") }
        /// Handwritten
        public static var fontHandwritten: String { Strings.shared.string("tweaks.fontHandwritten") }
        /// Card density
        public static var cardDensity: String { Strings.shared.string("tweaks.cardDensity") }
        /// Normal (3 col)
        public static var densityNormal: String { Strings.shared.string("tweaks.densityNormal") }
        /// Compact (4 col)
        public static var densityCompact: String { Strings.shared.string("tweaks.densityCompact") }
        /// Airy (2 col)
        public static var densityAiry: String { Strings.shared.string("tweaks.densityAiry") }
        /// Grain
        public static var grainIntensity: String { Strings.shared.string("tweaks.grainIntensity") }
        /// None
        public static var grainNone: String { Strings.shared.string("tweaks.grainNone") }
        /// Soft
        public static var grainSoft: String { Strings.shared.string("tweaks.grainSoft") }
        /// Medium
        public static var grainMedium: String { Strings.shared.string("tweaks.grainMedium") }
        /// Heavy
        public static var grainHeavy: String { Strings.shared.string("tweaks.grainHeavy") }
    }
    public enum App {
        public enum Nav {
            /// Resonance Feed
            public static var home: String { Strings.shared.string("app.nav.home") }
            /// My Card Box
            public static var me: String { Strings.shared.string("app.nav.me") }
            /// Write
            public static var write: String { Strings.shared.string("app.nav.write") }
            /// Notifications
            public static var notifications: String { Strings.shared.string("app.nav.notifications") }
            /// Settings
            public static var settings: String { Strings.shared.string("app.nav.settings") }
            /// Sign in
            public static var signIn: String { Strings.shared.string("app.nav.signIn") }
            /// Sign out
            public static var signOut: String { Strings.shared.string("app.nav.signOut") }
            /// Messages
            public static var messages: String { Strings.shared.string("app.nav.messages") }
            /// Back
            public static var back: String { Strings.shared.string("app.nav.back") }
            /// Open menu
            public static var openMenu: String { Strings.shared.string("app.nav.openMenu") }
            /// Edit this card
            public static var editThisCard: String { Strings.shared.string("app.nav.editThisCard") }
        }
        public enum Notifications {
            /// When someone resonates with your card — or sends you a little note — it will show up here.
            public static var empty: String { Strings.shared.string("app.notifications.empty") }
            /// {handle} wants to connect
            public static func invite(handle: String) -> String { Strings.shared.format("app.notifications.invite", ["handle": handle]) }
            /// {handle} accepted your invite — you're connected ✿
            public static func inviteAccepted(handle: String) -> String { Strings.shared.format("app.notifications.inviteAccepted", ["handle": handle]) }
            /// {count} people resonated with you yesterday
            public static func resonanceSummary(count: Int) -> String { Strings.shared.format("app.notifications.resonanceSummary", ["count": count]) }
            /// Translation complete
            public static var translationDone: String { Strings.shared.string("app.notifications.translationDone") }
            /// {handle} resonated with your card
            public static func resonance(handle: String) -> String { Strings.shared.format("app.notifications.resonance", ["handle": handle]) }
            /// {handle} sent you a little note
            public static func note(handle: String) -> String { Strings.shared.format("app.notifications.note", ["handle": handle]) }
            /// {handle} linked a card to your card
            public static func cardLink(handle: String) -> String { Strings.shared.format("app.notifications.cardLink", ["handle": handle]) }
            /// Connect with them
            public static var connect: String { Strings.shared.string("app.notifications.connect") }
            /// Connected
            public static var alreadyConnected: String { Strings.shared.string("app.notifications.alreadyConnected") }
            /// View all
            public static var viewAll: String { Strings.shared.string("app.notifications.viewAll") }
            /// {handle} sent you a message.
            public static func message(handle: String) -> String { Strings.shared.format("app.notifications.message", ["handle": handle]) }
        }
        public enum SignOutConfirm {
            /// Sign out?
            public static var title: String { Strings.shared.string("app.signOutConfirm.title") }
            /// You'll need to sign in again to get back to your card box.
            public static var body: String { Strings.shared.string("app.signOutConfirm.body") }
            /// Sign out
            public static var confirm: String { Strings.shared.string("app.signOutConfirm.confirm") }
            /// Cancel
            public static var cancel: String { Strings.shared.string("app.signOutConfirm.cancel") }
        }
        /// {count} min
        public static func readMinutes(count: Int) -> String { Strings.shared.format("app.readMinutes", ["count": count]) }
    }
    public enum Home {
        /// Stories picked for you
        public static var heading: String { Strings.shared.string("home.heading") }
        /// Chosen from the insights you have written, alongside the newest public cards.
        public static var subheading: String { Strings.shared.string("home.subheading") }
        /// Load more
        public static var moreBtn: String { Strings.shared.string("home.moreBtn") }
        /// Loading…
        public static var moreLoading: String { Strings.shared.string("home.moreLoading") }
        /// You are caught up on the latest public cards
        public static var endOfDay: String { Strings.shared.string("home.endOfDay") }
        /// Write a card
        public static var writeResponse: String { Strings.shared.string("home.writeResponse") }
        public enum Empty {
            /// Write your first card
            public static var title: String { Strings.shared.string("home.empty.title") }
            /// Once published, it can appear in the latest public feed.
            public static var subtitle: String { Strings.shared.string("home.empty.subtitle") }
            /// Start writing
            public static var cta: String { Strings.shared.string("home.empty.cta") }
        }
        /// because of “{reason}”
        public static func matchReason(reason: String) -> String { Strings.shared.format("home.matchReason", ["reason": reason]) }
        public enum Recommended {
            /// The insights you write decide which stories find you.
            public static var hint: String { Strings.shared.string("home.recommended.hint") }
            /// Today's picks are ready
            public static var ready: String { Strings.shared.string("home.recommended.ready") }
        }
        public enum ColdStart {
            /// Your first card becomes the point this world starts arranging itself around.
            public static var title: String { Strings.shared.string("home.coldStart.title") }
            /// Write a story
            public static var cta: String { Strings.shared.string("home.coldStart.cta") }
        }
    }
    public enum Card {
        /// Resonate
        public static var resonate: String { Strings.shared.string("card.resonate") }
        /// Resonated
        public static var resonated: String { Strings.shared.string("card.resonated") }
        /// Edit
        public static var modify: String { Strings.shared.string("card.modify") }
        /// Publish
        public static var publishResonance: String { Strings.shared.string("card.publishResonance") }
        /// Save draft
        public static var saveResonanceDraft: String { Strings.shared.string("card.saveResonanceDraft") }
        /// Cards linked to this
        public static var linkedCards: String { Strings.shared.string("card.linkedCards") }
        /// Resonated by
        public static var resonatedBy: String { Strings.shared.string("card.resonatedBy") }
        /// View all
        public static var viewAllResonators: String { Strings.shared.string("card.viewAllResonators") }
        /// No one has resonated with this card yet.
        public static var noResonatorsYet: String { Strings.shared.string("card.noResonatorsYet") }
        /// No bio yet.
        public static var noBio: String { Strings.shared.string("card.noBio") }
        public enum Resonance {
            /// Reflections on \"{title}\"
            public static func titlePrefill(title: String) -> String { Strings.shared.format("card.resonance.titlePrefill", ["title": title]) }
            /// Your response becomes a card of your own.
            public static var hint: String { Strings.shared.string("card.resonance.hint") }
            /// Not ready to go public? Send it to the author as a note instead.
            public static var downgrade: String { Strings.shared.string("card.resonance.downgrade") }
            /// The insight of this card is \"{coreInsight}\". Have you lived something similar — or the exact opposite?
            public static func aiPrompt(coreInsight: String) -> String { Strings.shared.format("card.resonance.aiPrompt", ["coreInsight": coreInsight]) }
        }
        public enum Note {
            /// Send the author a little note
            public static var entry: String { Strings.shared.string("card.note.entry") }
            /// A little note
            public static var label: String { Strings.shared.string("card.note.label") }
            /// Something you want to tell the author…
            public static var placeholder: String { Strings.shared.string("card.note.placeholder") }
            /// Only the author can see this.
            public static var hint: String { Strings.shared.string("card.note.hint") }
            /// Want to turn this into a resonance card?
            public static var upgrade: String { Strings.shared.string("card.note.upgrade") }
            /// Your note is on its way.
            public static var sent: String { Strings.shared.string("card.note.sent") }
            /// Send
            public static var send: String { Strings.shared.string("card.note.send") }
            /// Cancel
            public static var cancel: String { Strings.shared.string("card.note.cancel") }
            /// Close
            public static var close: String { Strings.shared.string("card.note.close") }
        }
        public enum Bookmark {
            /// Saved
            public static var saved: String { Strings.shared.string("card.bookmark.saved") }
            /// Bookmark
            public static var add: String { Strings.shared.string("card.bookmark.add") }
            /// Remove bookmark
            public static var remove: String { Strings.shared.string("card.bookmark.remove") }
        }
        public enum ResonanceSection {
            /// Cards resonating with this
            public static var title: String { Strings.shared.string("card.resonanceSection.title") }
            /// Resonating with
            public static var sourceTitle: String { Strings.shared.string("card.resonanceSection.sourceTitle") }
            /// No one has resonated with this card yet — be the first.
            public static var empty: String { Strings.shared.string("card.resonanceSection.empty") }
        }
        public enum LinkModal {
            /// Link with a card
            public static var title: String { Strings.shared.string("card.linkModal.title") }
            /// Pick one of your cards to link with this one.
            public static var pickCard: String { Strings.shared.string("card.linkModal.pickCard") }
            /// Create link
            public static var confirm: String { Strings.shared.string("card.linkModal.confirm") }
            /// Cancel
            public static var cancel: String { Strings.shared.string("card.linkModal.cancel") }
            /// Close
            public static var close: String { Strings.shared.string("card.linkModal.close") }
            /// Linked!
            public static var linked: String { Strings.shared.string("card.linkModal.linked") }
            /// You have no published cards to link yet.
            public static var noCards: String { Strings.shared.string("card.linkModal.noCards") }
        }
        public enum ResonatorsModal {
            /// Resonated with this card
            public static var title: String { Strings.shared.string("card.resonatorsModal.title") }
        }
        /// Translate to
        public static var translateTo: String { Strings.shared.string("card.translateTo") }
        /// Show original
        public static var showOriginal: String { Strings.shared.string("card.showOriginal") }
        /// Extended cards
        public static var related: String { Strings.shared.string("card.related") }
        /// Contents
        public static var toc: String { Strings.shared.string("card.toc") }
        public enum AuthorMetrics {
            /// Only you see this
            public static var title: String { Strings.shared.string("card.authorMetrics.title") }
            /// Reads
            public static var reads: String { Strings.shared.string("card.authorMetrics.reads") }
            /// Resonances
            public static var resonances: String { Strings.shared.string("card.authorMetrics.resonances") }
            /// Invites
            public static var inviteRequests: String { Strings.shared.string("card.authorMetrics.inviteRequests") }
        }
        /// Verified
        public static var verified: String { Strings.shared.string("card.verified") }
        /// Share
        public static var share: String { Strings.shared.string("card.share") }
        /// Private
        public static var `private`: String { Strings.shared.string("card.private") }
        /// Connections only
        public static var connections: String { Strings.shared.string("card.connections") }
        public enum NotFound {
            /// This card can't be found
            public static var title: String { Strings.shared.string("card.notFound.title") }
            /// Back to home
            public static var back: String { Strings.shared.string("card.notFound.back") }
        }
        /// Anonymous
        public static var anonymousAuthor: String { Strings.shared.string("card.anonymousAuthor") }
        /// This card was published anonymously — your pen name isn't shown on it or on your profile.
        public static var anonymousOwnerNote: String { Strings.shared.string("card.anonymousOwnerNote") }
    }
    public enum Messages {
        /// Messages
        public static var title: String { Strings.shared.string("messages.title") }
        /// Quiet conversations with the people you're connected with.
        public static var subtitle: String { Strings.shared.string("messages.subtitle") }
        /// Once you form a connection, your conversations will live here.
        public static var empty: String { Strings.shared.string("messages.empty") }
        /// Connected — no conversation yet
        public static var startSection: String { Strings.shared.string("messages.startSection") }
        /// Pick a conversation from the left.
        public static var pickOne: String { Strings.shared.string("messages.pickOne") }
        /// No messages yet — say hello.
        public static var noMessagesYet: String { Strings.shared.string("messages.noMessagesYet") }
        /// Write a message…
        public static var placeholder: String { Strings.shared.string("messages.placeholder") }
        /// Send
        public static var send: String { Strings.shared.string("messages.send") }
        /// Couldn't send — please try again.
        public static var sendError: String { Strings.shared.string("messages.sendError") }
        /// You can only message people you're connected with.
        public static var notConnected: String { Strings.shared.string("messages.notConnected") }
        /// View profile
        public static var viewProfile: String { Strings.shared.string("messages.viewProfile") }
        /// All conversations
        public static var back: String { Strings.shared.string("messages.back") }
        /// You: 
        public static var youPrefix: String { Strings.shared.string("messages.youPrefix") }
        /// This person doesn't exist.
        public static var userNotFound: String { Strings.shared.string("messages.userNotFound") }
        /// Conversation with {handle}
        public static func threadWith(handle: String) -> String { Strings.shared.format("messages.threadWith", ["handle": handle]) }
        /// Message
        public static var messageLink: String { Strings.shared.string("messages.messageLink") }
        /// Start chatting
        public static var startChat: String { Strings.shared.string("messages.startChat") }
        /// Reply
        public static var replyToNote: String { Strings.shared.string("messages.replyToNote") }
        /// In reply to your note
        public static var quotedNote: String { Strings.shared.string("messages.quotedNote") }
        /// Attach a card
        public static var attachCard: String { Strings.shared.string("messages.attachCard") }
        /// Remove card
        public static var removeCard: String { Strings.shared.string("messages.removeCard") }
        /// Shared a card
        public static var cardShared: String { Strings.shared.string("messages.cardShared") }
        /// Share one of your cards
        public static var pickCard: String { Strings.shared.string("messages.pickCard") }
        /// Share one of your published cards in this conversation.
        public static var pickCardSubtitle: String { Strings.shared.string("messages.pickCardSubtitle") }
        /// Conversation options
        public static var moreMenu: String { Strings.shared.string("messages.moreMenu") }
        /// Search messages
        public static var menuSearch: String { Strings.shared.string("messages.menuSearch") }
        /// Cards & links
        public static var menuMedia: String { Strings.shared.string("messages.menuMedia") }
        /// Delete conversation
        public static var menuDelete: String { Strings.shared.string("messages.menuDelete") }
        /// Search this conversation…
        public static var searchPlaceholder: String { Strings.shared.string("messages.searchPlaceholder") }
        /// {count, plural, =0 {No matches} one {# match} other {# matches}}
        public static func searchCount(count: Int) -> String { Strings.shared.format("messages.searchCount", ["count": count]) }
        /// Close search
        public static var searchClose: String { Strings.shared.string("messages.searchClose") }
        /// Cards & links
        public static var mediaTitle: String { Strings.shared.string("messages.mediaTitle") }
        /// Everything shared in this conversation.
        public static var mediaSubtitle: String { Strings.shared.string("messages.mediaSubtitle") }
        /// Shared cards
        public static var mediaCards: String { Strings.shared.string("messages.mediaCards") }
        /// Links
        public static var mediaLinks: String { Strings.shared.string("messages.mediaLinks") }
        /// Nothing shared here yet.
        public static var mediaEmpty: String { Strings.shared.string("messages.mediaEmpty") }
        /// Delete this conversation?
        public static var deleteConfirmTitle: String { Strings.shared.string("messages.deleteConfirmTitle") }
        /// This removes the whole conversation for both of you. It can’t be undone.
        public static var deleteConfirmBody: String { Strings.shared.string("messages.deleteConfirmBody") }
        /// Keep it
        public static var deleteCancel: String { Strings.shared.string("messages.deleteCancel") }
        /// Delete
        public static var deleteConfirm: String { Strings.shared.string("messages.deleteConfirm") }
        /// Couldn’t delete — please try again.
        public static var deleteError: String { Strings.shared.string("messages.deleteError") }
    }
    public enum Write {
        /// Give it a one-line title first.
        public static var titleRequired: String { Strings.shared.string("write.titleRequired") }
        /// New card
        public static var title: String { Strings.shared.string("write.title") }
        /// Edit draft
        public static var editTitle: String { Strings.shared.string("write.editTitle") }
        /// Edit a published card
        public static var editPublishedTitle: String { Strings.shared.string("write.editPublishedTitle") }
        /// Close editor
        public static var closeEditor: String { Strings.shared.string("write.closeEditor") }
        /// Leave for now?
        public static var leaveTitle: String { Strings.shared.string("write.leaveTitle") }
        /// What you've written is saved as a draft. You can pick it up again from My Card Box.
        public static var leaveBody: String { Strings.shared.string("write.leaveBody") }
        /// Your changes are saved, but not yet applied to the published card.
        public static var leaveBodyRevision: String { Strings.shared.string("write.leaveBodyRevision") }
        /// Keep writing
        public static var leaveStay: String { Strings.shared.string("write.leaveStay") }
        /// Leave
        public static var leaveConfirm: String { Strings.shared.string("write.leaveConfirm") }
        /// Drag to resize panes
        public static var resizeDivider: String { Strings.shared.string("write.resizeDivider") }
        /// Original Article
        public static var referenceCard: String { Strings.shared.string("write.referenceCard") }
        /// One-line title
        public static var coreLabel: String { Strings.shared.string("write.coreLabel") }
        /// e.g. Being seen matters more than being liked.
        public static var corePlaceholder: String { Strings.shared.string("write.corePlaceholder") }
        /// Story
        public static var storyLabel: String { Strings.shared.string("write.storyLabel") }
        /// Write the moment that pulled that line out of you…
        public static var storyPlaceholder: String { Strings.shared.string("write.storyPlaceholder") }
        public enum Editor {
            /// Editor toolbar
            public static var toolbarLabel: String { Strings.shared.string("write.editor.toolbarLabel") }
            /// Bold
            public static var bold: String { Strings.shared.string("write.editor.bold") }
            /// Italic
            public static var italic: String { Strings.shared.string("write.editor.italic") }
            /// Heading 2
            public static var h2: String { Strings.shared.string("write.editor.h2") }
            /// Heading 3
            public static var h3: String { Strings.shared.string("write.editor.h3") }
            /// List
            public static var bulletList: String { Strings.shared.string("write.editor.bulletList") }
            /// Numbered
            public static var orderedList: String { Strings.shared.string("write.editor.orderedList") }
            /// Quote
            public static var quote: String { Strings.shared.string("write.editor.quote") }
            /// Insert card
            public static var insertCard: String { Strings.shared.string("write.editor.insertCard") }
            /// Insert image
            public static var insertImage: String { Strings.shared.string("write.editor.insertImage") }
            /// Uploading image…
            public static var imageUploading: String { Strings.shared.string("write.editor.imageUploading") }
            /// Image upload failed. Please try again.
            public static var imageUploadError: String { Strings.shared.string("write.editor.imageUploadError") }
            /// Remove image
            public static var removeImage: String { Strings.shared.string("write.editor.removeImage") }
            /// Remove card
            public static var removeCard: String { Strings.shared.string("write.editor.removeCard") }
            public enum CardModal {
                /// Insert a card link
                public static var title: String { Strings.shared.string("write.editor.cardModal.title") }
                /// Pick one of your public cards — the link lands at your cursor.
                public static var subtitle: String { Strings.shared.string("write.editor.cardModal.subtitle") }
                /// You have no public cards yet.
                public static var empty: String { Strings.shared.string("write.editor.cardModal.empty") }
                /// Cancel
                public static var cancel: String { Strings.shared.string("write.editor.cardModal.cancel") }
            }
        }
        /// Tags
        public static var tagsLabel: String { Strings.shared.string("write.tagsLabel") }
        /// AI: suggest 2–3
        public static var tagsSuggest: String { Strings.shared.string("write.tagsSuggest") }
        /// Thinking…
        public static var tagsSuggesting: String { Strings.shared.string("write.tagsSuggesting") }
        /// Couldn’t suggest tags. Please try again.
        public static var tagsSuggestError: String { Strings.shared.string("write.tagsSuggestError") }
        /// Type a tag…
        public static var tagsPlaceholder: String { Strings.shared.string("write.tagsPlaceholder") }
        /// Add
        public static var tagsAdd: String { Strings.shared.string("write.tagsAdd") }
        /// Image (optional)
        public static var mediaLabel: String { Strings.shared.string("write.mediaLabel") }
        /// Remove image
        public static var mediaRemove: String { Strings.shared.string("write.mediaRemove") }
        /// Click, or drag an image here
        public static var mediaPlaceholder: String { Strings.shared.string("write.mediaPlaceholder") }
        /// PNG, JPG, WebP · up to 5MB
        public static var mediaHint: String { Strings.shared.string("write.mediaHint") }
        /// Image upload failed. Please try again.
        public static var mediaUploadError: String { Strings.shared.string("write.mediaUploadError") }
        /// Sketching it in…
        public static var mediaUploading: String { Strings.shared.string("write.mediaUploading") }
        /// Generate
        public static var mediaGenerate: String { Strings.shared.string("write.mediaGenerate") }
        /// An image from your story
        public static var mediaGenerateHint: String { Strings.shared.string("write.mediaGenerateHint") }
        /// Write your story first
        public static var mediaGenerateNeedStory: String { Strings.shared.string("write.mediaGenerateNeedStory") }
        /// Imagining a scene…
        public static var mediaGenerating: String { Strings.shared.string("write.mediaGenerating") }
        /// Couldn’t generate an image. Please try again.
        public static var mediaGenerateError: String { Strings.shared.string("write.mediaGenerateError") }
        /// AI-generated illustration
        public static var mediaGeneratedLabel: String { Strings.shared.string("write.mediaGeneratedLabel") }
        public enum Visibility {
            /// Who can see
            public static var label: String { Strings.shared.string("write.visibility.label") }
            /// Public
            public static var `public`: String { Strings.shared.string("write.visibility.public") }
            /// Connections only
            public static var connections: String { Strings.shared.string("write.visibility.connections") }
            /// Only me
            public static var `private`: String { Strings.shared.string("write.visibility.private") }
        }
        public enum Ai {
            /// AI writing partner
            public static var panel: String { Strings.shared.string("write.ai.panel") }
            /// Polish
            public static var polish: String { Strings.shared.string("write.ai.polish") }
            /// Keep your voice, just smooth the prose
            public static var polishHint: String { Strings.shared.string("write.ai.polishHint") }
            /// Title ideas
            public static var title: String { Strings.shared.string("write.ai.title") }
            /// 3 candidates for the core thought
            public static var titleHint: String { Strings.shared.string("write.ai.titleHint") }
            /// Generate tags
            public static var tags: String { Strings.shared.string("write.ai.tags") }
            /// Concepts, not keywords
            public static var tagsHint: String { Strings.shared.string("write.ai.tagsHint") }
            /// Use
            public static var apply: String { Strings.shared.string("write.ai.apply") }
            /// Keep mine
            public static var keep: String { Strings.shared.string("write.ai.keep") }
            /// Try again
            public static var regenerate: String { Strings.shared.string("write.ai.regenerate") }
            /// (MVP AI is a stub; real model in Phase 3)
            public static var stubNotice: String { Strings.shared.string("write.ai.stubNotice") }
        }
        /// Publish
        public static var publish: String { Strings.shared.string("write.publish") }
        /// Publishing…
        public static var publishing: String { Strings.shared.string("write.publishing") }
        /// Draft saved · {time}
        public static func autosaved(time: String) -> String { Strings.shared.format("write.autosaved", ["time": time]) }
        /// This card is already published. Changes are kept privately until you press Save changes.
        public static var editLiveHint: String { Strings.shared.string("write.editLiveHint") }
        /// Changes saved privately · {time} (readers still see the old version)
        public static func editBuffered(time: String) -> String { Strings.shared.format("write.editBuffered", ["time": time]) }
        /// You have unsaved changes here — only you can see them.
        public static var editBufferedIdle: String { Strings.shared.string("write.editBufferedIdle") }
        /// Save draft and leave
        public static var saveDraftAndLeave: String { Strings.shared.string("write.saveDraftAndLeave") }
        /// Save changes
        public static var saveChanges: String { Strings.shared.string("write.saveChanges") }
        /// Saving…
        public static var saving: String { Strings.shared.string("write.saving") }
        /// Discard changes
        public static var discardChanges: String { Strings.shared.string("write.discardChanges") }
        public enum PublishPanel {
            /// Publish this card
            public static var title: String { Strings.shared.string("write.publishPanel.title") }
            /// Reading your story…
            public static var insightLoading: String { Strings.shared.string("write.publishPanel.insightLoading") }
            /// What you seem to be saying — “{coreInsight}”
            public static func insight(coreInsight: String) -> String { Strings.shared.format("write.publishPanel.insight", ["coreInsight": coreInsight]) }
            /// Publish anonymously
            public static var anonymousToggle: String { Strings.shared.string("write.publishPanel.anonymousToggle") }
            /// Anonymous
            public static var anonymousName: String { Strings.shared.string("write.publishPanel.anonymousName") }
            /// Anonymous cards never appear on your profile.
            public static var anonymousHint: String { Strings.shared.string("write.publishPanel.anonymousHint") }
            /// Publish
            public static var publish: String { Strings.shared.string("write.publishPanel.publish") }
            /// Publishing…
            public static var publishing: String { Strings.shared.string("write.publishPanel.publishing") }
            /// Not yet
            public static var cancel: String { Strings.shared.string("write.publishPanel.cancel") }
            /// Update this card
            public static var updateTitle: String { Strings.shared.string("write.publishPanel.updateTitle") }
            /// After this, readers see this version. The publish date stays as it was.
            public static var updateHint: String { Strings.shared.string("write.publishPanel.updateHint") }
            /// Save changes
            public static var update: String { Strings.shared.string("write.publishPanel.update") }
            /// Saving…
            public static var updating: String { Strings.shared.string("write.publishPanel.updating") }
        }
        public enum FirstCard {
            /// Write your first card
            public static var title: String { Strings.shared.string("write.firstCard.title") }
            /// Not sure where to start? Pick a question and write what surfaces.
            public static var intro: String { Strings.shared.string("write.firstCard.intro") }
            /// What small moment recently changed how you see something?
            public static var q1: String { Strings.shared.string("write.firstCard.q1") }
            /// What is one thing you wish you could tell your past self?
            public static var q2: String { Strings.shared.string("write.firstCard.q2") }
            /// Which failure taught you something nobody else ever did?
            public static var q3: String { Strings.shared.string("write.firstCard.q3") }
        }
    }
    public enum Me {
        /// Joined {date}
        public static func joined(date: String) -> String { Strings.shared.format("me.joined", ["date": date]) }
        /// Edit profile
        public static var editProfile: String { Strings.shared.string("me.editProfile") }
        /// View public profile
        public static var viewPublicProfile: String { Strings.shared.string("me.viewPublicProfile") }
        /// No bio yet.
        public static var bioEmpty: String { Strings.shared.string("me.bioEmpty") }
        public enum Tabs {
            /// Published
            public static var published: String { Strings.shared.string("me.tabs.published") }
            /// Private
            public static var `private`: String { Strings.shared.string("me.tabs.private") }
            /// Drafts
            public static var draft: String { Strings.shared.string("me.tabs.draft") }
            /// Resonated
            public static var resonated: String { Strings.shared.string("me.tabs.resonated") }
            /// Linked
            public static var linked: String { Strings.shared.string("me.tabs.linked") }
            /// Bookmarks
            public static var bookmarks: String { Strings.shared.string("me.tabs.bookmarks") }
            /// Thought map
            public static var thoughtMap: String { Strings.shared.string("me.tabs.thoughtMap") }
        }
        public enum ThoughtMap {
            /// Bring your cards onto the map and start weaving your thoughts together.
            public static var empty: String { Strings.shared.string("me.thoughtMap.empty") }
            /// Add card
            public static var addCard: String { Strings.shared.string("me.thoughtMap.addCard") }
            /// Card
            public static var addCardShort: String { Strings.shared.string("me.thoughtMap.addCardShort") }
            /// New group
            public static var addGroup: String { Strings.shared.string("me.thoughtMap.addGroup") }
            /// Group
            public static var addGroupShort: String { Strings.shared.string("me.thoughtMap.addGroupShort") }
            /// Untitled group
            public static var newGroup: String { Strings.shared.string("me.thoughtMap.newGroup") }
            /// Pick a card to add
            public static var trayTitle: String { Strings.shared.string("me.thoughtMap.trayTitle") }
            /// Every card is already on the map.
            public static var trayEmpty: String { Strings.shared.string("me.thoughtMap.trayEmpty") }
            /// Zoom in
            public static var zoomIn: String { Strings.shared.string("me.thoughtMap.zoomIn") }
            /// Zoom out
            public static var zoomOut: String { Strings.shared.string("me.thoughtMap.zoomOut") }
            /// Fit to view
            public static var zoomFit: String { Strings.shared.string("me.thoughtMap.zoomFit") }
            /// Open
            public static var `open`: String { Strings.shared.string("me.thoughtMap.open") }
            /// Remove from map
            public static var removeFromMap: String { Strings.shared.string("me.thoughtMap.removeFromMap") }
            /// Delete connection
            public static var deleteEdge: String { Strings.shared.string("me.thoughtMap.deleteEdge") }
            /// Delete group
            public static var deleteGroup: String { Strings.shared.string("me.thoughtMap.deleteGroup") }
            /// What does this connection mean?
            public static var edgeLabelPlaceholder: String { Strings.shared.string("me.thoughtMap.edgeLabelPlaceholder") }
            /// Name this group
            public static var groupTitlePlaceholder: String { Strings.shared.string("me.thoughtMap.groupTitlePlaceholder") }
            /// Draw a connection
            public static var linkHandle: String { Strings.shared.string("me.thoughtMap.linkHandle") }
            /// Resize group
            public static var resizeGroup: String { Strings.shared.string("me.thoughtMap.resizeGroup") }
            /// Back to profile
            public static var back: String { Strings.shared.string("me.thoughtMap.back") }
            /// Leave
            public static var leave: String { Strings.shared.string("me.thoughtMap.leave") }
        }
        /// Your first card becomes the point this world starts arranging itself around.
        public static var emptyPublished: String { Strings.shared.string("me.emptyPublished") }
        /// No private cards.
        public static var emptyPrivate: String { Strings.shared.string("me.emptyPrivate") }
        /// No drafts.
        public static var emptyDraft: String { Strings.shared.string("me.emptyDraft") }
        /// No one has linked a card to you yet.
        public static var emptyLinked: String { Strings.shared.string("me.emptyLinked") }
        /// No resonances yet.
        public static var emptyResonated: String { Strings.shared.string("me.emptyResonated") }
        /// When a story is too good to forget, press the bookmark — it will wait here quietly, only for you.
        public static var emptyBookmarks: String { Strings.shared.string("me.emptyBookmarks") }
        public enum Actions {
            /// Manage card
            public static var menuLabel: String { Strings.shared.string("me.actions.menuLabel") }
            /// Edit
            public static var edit: String { Strings.shared.string("me.actions.edit") }
            /// Make public
            public static var makePublic: String { Strings.shared.string("me.actions.makePublic") }
            /// Make private
            public static var makePrivate: String { Strings.shared.string("me.actions.makePrivate") }
            /// Delete
            public static var delete: String { Strings.shared.string("me.actions.delete") }
            /// Delete this card?
            public static var deleteConfirmTitle: String { Strings.shared.string("me.actions.deleteConfirmTitle") }
            /// This cannot be undone — the story and its resonance links will be gone.
            public static var deleteConfirmBody: String { Strings.shared.string("me.actions.deleteConfirmBody") }
            /// Delete card
            public static var deleteConfirm: String { Strings.shared.string("me.actions.deleteConfirm") }
            /// Keep it
            public static var deleteCancel: String { Strings.shared.string("me.actions.deleteCancel") }
        }
        /// Anonymous
        public static var anonymousBadge: String { Strings.shared.string("me.anonymousBadge") }
        /// Write a story
        public static var emptyPublishedCta: String { Strings.shared.string("me.emptyPublishedCta") }
        /// Show
        public static var filterLabel: String { Strings.shared.string("me.filterLabel") }
    }
    public enum Profile {
        /// Not connected
        public static var notConnected: String { Strings.shared.string("profile.notConnected") }
        /// Connected
        public static var connected: String { Strings.shared.string("profile.connected") }
        /// Message
        public static var message: String { Strings.shared.string("profile.message") }
        /// More cards, saved for those who connect ✿
        public static var softLock: String { Strings.shared.string("profile.softLock") }
        /// Cards linked to them
        public static var linkedCards: String { Strings.shared.string("profile.linkedCards") }
        /// ⋯
        public static var more: String { Strings.shared.string("profile.more") }
        /// Report
        public static var report: String { Strings.shared.string("profile.report") }
        /// Block
        public static var block: String { Strings.shared.string("profile.block") }
        /// Disconnect
        public static var disconnect: String { Strings.shared.string("profile.disconnect") }
        /// Translating…
        public static var translating: String { Strings.shared.string("profile.translating") }
        /// Show original
        public static var showOriginal: String { Strings.shared.string("profile.showOriginal") }
        /// This person can't be found
        public static var notFound: String { Strings.shared.string("profile.notFound") }
        /// Back to home
        public static var backHome: String { Strings.shared.string("profile.backHome") }
        /// {handle} · Resonance
        public static func shareTitle(handle: String) -> String { Strings.shared.format("profile.shareTitle", ["handle": handle]) }
        /// {handle}'s life stories on Resonance
        public static func shareDescription(handle: String) -> String { Strings.shared.format("profile.shareDescription", ["handle": handle]) }
        /// No bio yet.
        public static var bioEmpty: String { Strings.shared.string("profile.bioEmpty") }
        /// Joined {date}
        public static func joined(date: String) -> String { Strings.shared.format("profile.joined", ["date": date]) }
        /// Edit profile
        public static var editProfile: String { Strings.shared.string("profile.editProfile") }
        /// {count, plural, =0 {No public cards} one {# public card} other {# public cards}}
        public static func cardCount(count: Int) -> String { Strings.shared.format("profile.cardCount", ["count": count]) }
        /// Published
        public static var publishedHeading: String { Strings.shared.string("profile.publishedHeading") }
        /// Nothing published yet.
        public static var emptyPublished: String { Strings.shared.string("profile.emptyPublished") }
        /// Your first card becomes the point this world starts arranging itself around.
        public static var emptyPublishedSelf: String { Strings.shared.string("profile.emptyPublishedSelf") }
        /// Write a story
        public static var emptyPublishedCta: String { Strings.shared.string("profile.emptyPublishedCta") }
    }
    public enum Invite {
        /// Invite to connect
        public static var title: String { Strings.shared.string("invite.title") }
        /// Reference a card (optional)
        public static var referenceCard: String { Strings.shared.string("invite.referenceCard") }
        /// None
        public static var noReference: String { Strings.shared.string("invite.noReference") }
        /// Say one thing (required, 14–140 chars)
        public static var messageLabel: String { Strings.shared.string("invite.messageLabel") }
        /// Let them know why you want to connect…
        public static var messagePlaceholder: String { Strings.shared.string("invite.messagePlaceholder") }
        /// {n} invites left today
        public static func quota(n: Int) -> String { Strings.shared.format("invite.quota", ["n": n]) }
        /// Daily invite quota used up. Try tomorrow.
        public static var quotaFull: String { Strings.shared.string("invite.quotaFull") }
        /// Send invite
        public static var send: String { Strings.shared.string("invite.send") }
        /// Cancel
        public static var cancel: String { Strings.shared.string("invite.cancel") }
        /// Waiting for their response
        public static var sent: String { Strings.shared.string("invite.sent") }
        /// {handle} wants to connect
        public static func receivedTitle(handle: String) -> String { Strings.shared.format("invite.receivedTitle", ["handle": handle]) }
        /// Accept
        public static var accept: String { Strings.shared.string("invite.accept") }
        /// Later
        public static var later: String { Strings.shared.string("invite.later") }
        /// See who
        public static var seeWho: String { Strings.shared.string("invite.seeWho") }
        /// You’re connected ✿
        public static var successTitle: String { Strings.shared.string("invite.successTitle") }
        /// You can now see each other’s full card box and DM.
        public static var successSubtitle: String { Strings.shared.string("invite.successSubtitle") }
        /// {days} days to respond
        public static func expiresIn(days: Int) -> String { Strings.shared.format("invite.expiresIn", ["days": days]) }
    }
    public enum InviteInbox {
        /// {count} pending connection invite(s)
        public static func title(count: Int) -> String { Strings.shared.format("inviteInbox.title", ["count": count]) }
        /// Accept
        public static var accept: String { Strings.shared.string("inviteInbox.accept") }
        /// Decline
        public static var decline: String { Strings.shared.string("inviteInbox.decline") }
        /// respond by {date}
        public static func expiresAt(date: String) -> String { Strings.shared.format("inviteInbox.expiresAt", ["date": date]) }
        /// (No message)
        public static var emptyMessage: String { Strings.shared.string("inviteInbox.emptyMessage") }
    }
    public enum Auth {
        /// Welcome back
        public static var signInTitle: String { Strings.shared.string("auth.signInTitle") }
        /// First visit
        public static var signUpTitle: String { Strings.shared.string("auth.signUpTitle") }
        /// Email
        public static var email: String { Strings.shared.string("auth.email") }
        /// Password
        public static var password: String { Strings.shared.string("auth.password") }
        /// Send me a magic link
        public static var magicLink: String { Strings.shared.string("auth.magicLink") }
        /// Sign in
        public static var signIn: String { Strings.shared.string("auth.signIn") }
        /// Signing in…
        public static var signingIn: String { Strings.shared.string("auth.signingIn") }
        /// Create account
        public static var signUp: String { Strings.shared.string("auth.signUp") }
        /// Creating…
        public static var creating: String { Strings.shared.string("auth.creating") }
        /// Continue with Google
        public static var continueWithGoogle: String { Strings.shared.string("auth.continueWithGoogle") }
        /// Continue with Apple
        public static var continueWithApple: String { Strings.shared.string("auth.continueWithApple") }
        /// We use Google to sign you in. We never see your password.
        public static var googleIntro: String { Strings.shared.string("auth.googleIntro") }
        /// We use Apple or Google to sign you in. We never see your password.
        public static var appleGoogleIntro: String { Strings.shared.string("auth.appleGoogleIntro") }
        /// Sign in failed. Please try again.
        public static var signInError: String { Strings.shared.string("auth.signInError") }
        /// Could not create the account. Please try again.
        public static var signUpError: String { Strings.shared.string("auth.signUpError") }
        /// No account yet?
        public static var switchToSignUp: String { Strings.shared.string("auth.switchToSignUp") }
        /// Already have one?
        public static var switchToSignIn: String { Strings.shared.string("auth.switchToSignIn") }
        /// Step {current} / {total}
        public static func step(current: Int, total: Int) -> String { Strings.shared.format("auth.step", ["current": current, "total": total]) }
        /// Email
        public static var stepEmail: String { Strings.shared.string("auth.stepEmail") }
        /// Verify phone
        public static var stepPhone: String { Strings.shared.string("auth.stepPhone") }
        /// Pick a handle
        public static var stepHandle: String { Strings.shared.string("auth.stepHandle") }
        /// Phone number
        public static var phoneLabel: String { Strings.shared.string("auth.phoneLabel") }
        /// We use it to check you’re a real person. Never shown publicly.
        public static var phoneHint: String { Strings.shared.string("auth.phoneHint") }
        /// SMS code
        public static var otpLabel: String { Strings.shared.string("auth.otpLabel") }
        /// Send code
        public static var otpSend: String { Strings.shared.string("auth.otpSend") }
        /// Resend
        public static var otpResend: String { Strings.shared.string("auth.otpResend") }
        /// Handle (2–20 chars)
        public static var handleLabel: String { Strings.shared.string("auth.handleLabel") }
        /// Available ✿
        public static var handleAvailable: String { Strings.shared.string("auth.handleAvailable") }
        /// Taken
        public static var handleTaken: String { Strings.shared.string("auth.handleTaken") }
        /// Checking…
        public static var handleChecking: String { Strings.shared.string("auth.handleChecking") }
        /// Where are you?
        public static var regionLabel: String { Strings.shared.string("auth.regionLabel") }
        /// Your main language
        public static var primaryLocaleLabel: String { Strings.shared.string("auth.primaryLocaleLabel") }
        /// Auto-translate my cards to:
        public static var autoTranslateLabel: String { Strings.shared.string("auth.autoTranslateLabel") }
        /// Next
        public static var next: String { Strings.shared.string("auth.next") }
        /// Back
        public static var back: String { Strings.shared.string("auth.back") }
        /// Finish
        public static var finish: String { Strings.shared.string("auth.finish") }
        /// Welcome, {handle}. Start with your first card.
        public static func welcome(handle: String) -> String { Strings.shared.format("auth.welcome", ["handle": handle]) }
        /// Your account is scheduled for deletion. Sign in within 7 days to cancel.
        public static var deletionScheduled: String { Strings.shared.string("auth.deletionScheduled") }
        /// By continuing, you agree to the {terms} and the {privacy}.
        public static func agreeTerms(terms: String, privacy: String) -> String { Strings.shared.format("auth.agreeTerms", ["terms": terms, "privacy": privacy]) }
        /// Terms of Use
        public static var termsLink: String { Strings.shared.string("auth.termsLink") }
        /// Privacy Policy
        public static var privacyLink: String { Strings.shared.string("auth.privacyLink") }
    }
    public enum Settings {
        /// Settings
        public static var title: String { Strings.shared.string("settings.title") }
        public enum Sections {
            /// Profile
            public static var profile: String { Strings.shared.string("settings.sections.profile") }
            /// Account
            public static var account: String { Strings.shared.string("settings.sections.account") }
            /// Privacy & connections
            public static var privacy: String { Strings.shared.string("settings.sections.privacy") }
            /// Notifications
            public static var notifications: String { Strings.shared.string("settings.sections.notifications") }
            /// Language
            public static var language: String { Strings.shared.string("settings.sections.language") }
            /// Appearance
            public static var appearance: String { Strings.shared.string("settings.sections.appearance") }
            /// AI writing partner
            public static var ai: String { Strings.shared.string("settings.sections.ai") }
            /// Terms
            public static var terms: String { Strings.shared.string("settings.sections.terms") }
            /// Delete account
            public static var delete: String { Strings.shared.string("settings.sections.delete") }
        }
        public enum Profile {
            /// Handle
            public static var handle: String { Strings.shared.string("settings.profile.handle") }
            /// One-line bio (≤ 80 chars)
            public static var bio: String { Strings.shared.string("settings.profile.bio") }
            /// Region
            public static var region: String { Strings.shared.string("settings.profile.region") }
            /// Profile photo
            public static var avatar: String { Strings.shared.string("settings.profile.avatar") }
            /// Click or drag an image here · PNG, JPG, WebP
            public static var avatarHint: String { Strings.shared.string("settings.profile.avatarHint") }
            /// Change profile photo
            public static var avatarChange: String { Strings.shared.string("settings.profile.avatarChange") }
            /// Sketching it in…
            public static var avatarUploading: String { Strings.shared.string("settings.profile.avatarUploading") }
            /// Upload failed. Please try again.
            public static var avatarError: String { Strings.shared.string("settings.profile.avatarError") }
        }
        public enum Account {
            /// Email
            public static var email: String { Strings.shared.string("settings.account.email") }
            /// Phone (verified)
            public static var phone: String { Strings.shared.string("settings.account.phone") }
            /// Password
            public static var password: String { Strings.shared.string("settings.account.password") }
            /// Sign out
            public static var signOut: String { Strings.shared.string("settings.account.signOut") }
        }
        public enum Privacy {
            /// Default publish scope
            public static var defaultVisibility: String { Strings.shared.string("settings.privacy.defaultVisibility") }
            /// Searchable by handle
            public static var searchable: String { Strings.shared.string("settings.privacy.searchable") }
            /// Let AI learn from my cards
            public static var aiOptIn: String { Strings.shared.string("settings.privacy.aiOptIn") }
            /// Manage blocks
            public static var manageBlocks: String { Strings.shared.string("settings.privacy.manageBlocks") }
        }
        public enum Notifications {
            /// Daily resonance summary
            public static var resonance: String { Strings.shared.string("settings.notifications.resonance") }
            /// Connection invites
            public static var connection: String { Strings.shared.string("settings.notifications.connection") }
            /// Direct messages
            public static var dm: String { Strings.shared.string("settings.notifications.dm") }
            /// Translation complete
            public static var translation: String { Strings.shared.string("settings.notifications.translation") }
        }
        public enum Language {
            /// UI language
            public static var ui: String { Strings.shared.string("settings.language.ui") }
            /// Primary writing language
            public static var original: String { Strings.shared.string("settings.language.original") }
            /// Auto-translate my cards
            public static var autoTranslate: String { Strings.shared.string("settings.language.autoTranslate") }
            /// When reading others’ cards
            public static var readPreference: String { Strings.shared.string("settings.language.readPreference") }
        }
        public enum Ai {
            /// Let AI polish my drafts
            public static var polish: String { Strings.shared.string("settings.ai.polish") }
            /// Let AI generate tags
            public static var tags: String { Strings.shared.string("settings.ai.tags") }
            /// Let AI offer hints on empty cards
            public static var hints: String { Strings.shared.string("settings.ai.hints") }
        }
        public enum Delete {
            /// Delete account
            public static var title: String { Strings.shared.string("settings.delete.title") }
            /// You'll be signed out right away. After 7 days your account, cards, messages and uploaded images are deleted for good; si
            public static var warn: String { Strings.shared.string("settings.delete.warn") }
            /// Before you go, you can download everything you've written.
            public static var exportHint: String { Strings.shared.string("settings.delete.exportHint") }
            /// Download my data
            public static var export: String { Strings.shared.string("settings.delete.export") }
            /// Preparing…
            public static var exporting: String { Strings.shared.string("settings.delete.exporting") }
            /// Delete account
            public static var button: String { Strings.shared.string("settings.delete.button") }
            /// Delete your account?
            public static var confirmTitle: String { Strings.shared.string("settings.delete.confirmTitle") }
            /// You'll be signed out. After {date}, your account and everything in it are deleted and can't be recovered.
            public static func confirmBody(date: String) -> String { Strings.shared.format("settings.delete.confirmBody", ["date": date]) }
            /// Delete account
            public static var confirm: String { Strings.shared.string("settings.delete.confirm") }
            /// Keep my account
            public static var cancel: String { Strings.shared.string("settings.delete.cancel") }
            /// That didn't go through. Try again.
            public static var error: String { Strings.shared.string("settings.delete.error") }
        }
    }
    public enum Safety {
        /// More options
        public static var menuLabel: String { Strings.shared.string("safety.menuLabel") }
        /// Report or block
        public static var reportOrBlock: String { Strings.shared.string("safety.reportOrBlock") }
        /// Report or unblock
        public static var reportOrUnblock: String { Strings.shared.string("safety.reportOrUnblock") }
        /// Report this card
        public static var reportCard: String { Strings.shared.string("safety.reportCard") }
        /// Report this person
        public static var reportUser: String { Strings.shared.string("safety.reportUser") }
        /// Report this conversation
        public static var reportMessage: String { Strings.shared.string("safety.reportMessage") }
        /// Block
        public static var block: String { Strings.shared.string("safety.block") }
        /// Unblock
        public static var unblock: String { Strings.shared.string("safety.unblock") }
        /// Block {handle}?
        public static func blockTitle(handle: String) -> String { Strings.shared.format("safety.blockTitle", ["handle": handle]) }
        /// They won't be able to message you, invite you or send you notes, and your connection will end. You won't see their cards
        public static var blockBody: String { Strings.shared.string("safety.blockBody") }
        /// Block
        public static var blockConfirm: String { Strings.shared.string("safety.blockConfirm") }
        /// Cancel
        public static var cancel: String { Strings.shared.string("safety.cancel") }
        /// That didn't work. Try again.
        public static var actionError: String { Strings.shared.string("safety.actionError") }
        /// this author
        public static var anonymousAuthor: String { Strings.shared.string("safety.anonymousAuthor") }
        /// You blocked {handle}
        public static func blockedNotice(handle: String) -> String { Strings.shared.format("safety.blockedNotice", ["handle": handle]) }
        /// You don't see their cards, and they can't reach you.
        public static var blockedNoticeBody: String { Strings.shared.string("safety.blockedNoticeBody") }
        public enum Report {
            /// Report this card
            public static var titleCard: String { Strings.shared.string("safety.report.titleCard") }
            /// Report {handle}
            public static func titleUser(handle: String) -> String { Strings.shared.format("safety.report.titleUser", ["handle": handle]) }
            /// Report your conversation with {handle}
            public static func titleMessage(handle: String) -> String { Strings.shared.format("safety.report.titleMessage", ["handle": handle]) }
            /// Tell us what happened. They won't know who reported them.
            public static var intro: String { Strings.shared.string("safety.report.intro") }
            /// Reason
            public static var reason: String { Strings.shared.string("safety.report.reason") }
            public enum Reasons {
                /// Spam or advertising
                public static var spam: String { Strings.shared.string("safety.report.reasons.spam") }
                /// Harassment or bullying
                public static var harassment: String { Strings.shared.string("safety.report.reasons.harassment") }
                /// Hate speech or discrimination
                public static var hate: String { Strings.shared.string("safety.report.reasons.hate") }
                /// Sexual or explicit content
                public static var sexual: String { Strings.shared.string("safety.report.reasons.sexual") }
                /// Self-harm or suicide
                public static var self_harm: String { Strings.shared.string("safety.report.reasons.self_harm") }
                /// Violence or threats
                public static var violence: String { Strings.shared.string("safety.report.reasons.violence") }
                /// Something else
                public static var other: String { Strings.shared.string("safety.report.reasons.other") }
            }
            /// Details (optional)
            public static var detail: String { Strings.shared.string("safety.report.detail") }
            /// What made you uncomfortable?
            public static var detailPlaceholder: String { Strings.shared.string("safety.report.detailPlaceholder") }
            /// Also block {handle}
            public static func alsoBlock(handle: String) -> String { Strings.shared.format("safety.report.alsoBlock", ["handle": handle]) }
            /// Send report
            public static var submit: String { Strings.shared.string("safety.report.submit") }
            /// Thanks for telling us
            public static var doneTitle: String { Strings.shared.string("safety.report.doneTitle") }
            /// We'll review it as soon as we can. If someone is in immediate danger, contact your local emergency services.
            public static var doneBody: String { Strings.shared.string("safety.report.doneBody") }
            /// You've also blocked {handle}.
            public static func doneBlocked(handle: String) -> String { Strings.shared.format("safety.report.doneBlocked", ["handle": handle]) }
            /// Close
            public static var close: String { Strings.shared.string("safety.report.close") }
        }
        public enum BlockedList {
            /// Blocked people
            public static var title: String { Strings.shared.string("safety.blockedList.title") }
            /// People you block can't reach you, and you don't see their cards.
            public static var subtitle: String { Strings.shared.string("safety.blockedList.subtitle") }
            /// You haven't blocked anyone.
            public static var empty: String { Strings.shared.string("safety.blockedList.empty") }
            /// Blocked {date}
            public static func since(date: String) -> String { Strings.shared.format("safety.blockedList.since", ["date": date]) }
            /// Deleted account
            public static var unknownUser: String { Strings.shared.string("safety.blockedList.unknownUser") }
            /// Close
            public static var close: String { Strings.shared.string("safety.blockedList.close") }
        }
    }
    public enum AccountDeletion {
        /// Your account will be deleted on {date}.
        public static func banner(date: String) -> String { Strings.shared.format("accountDeletion.banner", ["date": date]) }
        /// Cancel deletion
        public static var cancel: String { Strings.shared.string("accountDeletion.cancel") }
        /// Couldn't cancel. Try again.
        public static var error: String { Strings.shared.string("accountDeletion.error") }
    }
    public enum Native {
        /// Couldn't load this — please try again.
        public static var loadError: String { Strings.shared.string("native.loadError") }
        /// Copy
        public static var copy: String { Strings.shared.string("native.copy") }
        /// Couldn't save that — try again.
        public static var saveError: String { Strings.shared.string("native.saveError") }
        /// Try again
        public static var retry: String { Strings.shared.string("native.retry") }
        /// You're offline. What you've already opened is still here.
        public static var offline: String { Strings.shared.string("native.offline") }
        /// Feed
        public static var tabFeed: String { Strings.shared.string("native.tabFeed") }
    }
}
